// Code generated by go-swagger; DO NOT EDIT.

package public_ip

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreatePublicIPReader is a Reader for the CreatePublicIP structure.
type CreatePublicIPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePublicIPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreatePublicIPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreatePublicIPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreatePublicIPUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreatePublicIPInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreatePublicIPOK creates a CreatePublicIPOK with default headers values
func NewCreatePublicIPOK() *CreatePublicIPOK {
	return &CreatePublicIPOK{}
}

/*CreatePublicIPOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreatePublicIPOK struct {
}

func (o *CreatePublicIPOK) Error() string {
	return fmt.Sprintf("[POST /CreatePublicIp][%d] createPublicIpOK ", 200)
}

func (o *CreatePublicIPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePublicIPBadRequest creates a CreatePublicIPBadRequest with default headers values
func NewCreatePublicIPBadRequest() *CreatePublicIPBadRequest {
	return &CreatePublicIPBadRequest{}
}

/*CreatePublicIPBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type CreatePublicIPBadRequest struct {
}

func (o *CreatePublicIPBadRequest) Error() string {
	return fmt.Sprintf("[POST /CreatePublicIp][%d] createPublicIpBadRequest ", 400)
}

func (o *CreatePublicIPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePublicIPUnauthorized creates a CreatePublicIPUnauthorized with default headers values
func NewCreatePublicIPUnauthorized() *CreatePublicIPUnauthorized {
	return &CreatePublicIPUnauthorized{}
}

/*CreatePublicIPUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type CreatePublicIPUnauthorized struct {
}

func (o *CreatePublicIPUnauthorized) Error() string {
	return fmt.Sprintf("[POST /CreatePublicIp][%d] createPublicIpUnauthorized ", 401)
}

func (o *CreatePublicIPUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePublicIPInternalServerError creates a CreatePublicIPInternalServerError with default headers values
func NewCreatePublicIPInternalServerError() *CreatePublicIPInternalServerError {
	return &CreatePublicIPInternalServerError{}
}

/*CreatePublicIPInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type CreatePublicIPInternalServerError struct {
}

func (o *CreatePublicIPInternalServerError) Error() string {
	return fmt.Sprintf("[POST /CreatePublicIp][%d] createPublicIpInternalServerError ", 500)
}

func (o *CreatePublicIPInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
