// Code generated by go-swagger; DO NOT EDIT.

package public_ip

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreatePublicIPParams creates a new CreatePublicIPParams object
// with the default values initialized.
func NewCreatePublicIPParams() *CreatePublicIPParams {

	return &CreatePublicIPParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePublicIPParamsWithTimeout creates a new CreatePublicIPParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreatePublicIPParamsWithTimeout(timeout time.Duration) *CreatePublicIPParams {

	return &CreatePublicIPParams{

		timeout: timeout,
	}
}

// NewCreatePublicIPParamsWithContext creates a new CreatePublicIPParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreatePublicIPParamsWithContext(ctx context.Context) *CreatePublicIPParams {

	return &CreatePublicIPParams{

		Context: ctx,
	}
}

// NewCreatePublicIPParamsWithHTTPClient creates a new CreatePublicIPParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreatePublicIPParamsWithHTTPClient(client *http.Client) *CreatePublicIPParams {

	return &CreatePublicIPParams{
		HTTPClient: client,
	}
}

/*CreatePublicIPParams contains all the parameters to send to the API endpoint
for the create public Ip operation typically these are written to a http.Request
*/
type CreatePublicIPParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create public Ip params
func (o *CreatePublicIPParams) WithTimeout(timeout time.Duration) *CreatePublicIPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create public Ip params
func (o *CreatePublicIPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create public Ip params
func (o *CreatePublicIPParams) WithContext(ctx context.Context) *CreatePublicIPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create public Ip params
func (o *CreatePublicIPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create public Ip params
func (o *CreatePublicIPParams) WithHTTPClient(client *http.Client) *CreatePublicIPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create public Ip params
func (o *CreatePublicIPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePublicIPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
