// Code generated by go-swagger; DO NOT EDIT.

package public_ip

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeletePublicIPReader is a Reader for the DeletePublicIP structure.
type DeletePublicIPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePublicIPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePublicIPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeletePublicIPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeletePublicIPUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeletePublicIPInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeletePublicIPOK creates a DeletePublicIPOK with default headers values
func NewDeletePublicIPOK() *DeletePublicIPOK {
	return &DeletePublicIPOK{}
}

/*DeletePublicIPOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeletePublicIPOK struct {
}

func (o *DeletePublicIPOK) Error() string {
	return fmt.Sprintf("[POST /DeletePublicIp][%d] deletePublicIpOK ", 200)
}

func (o *DeletePublicIPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePublicIPBadRequest creates a DeletePublicIPBadRequest with default headers values
func NewDeletePublicIPBadRequest() *DeletePublicIPBadRequest {
	return &DeletePublicIPBadRequest{}
}

/*DeletePublicIPBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type DeletePublicIPBadRequest struct {
}

func (o *DeletePublicIPBadRequest) Error() string {
	return fmt.Sprintf("[POST /DeletePublicIp][%d] deletePublicIpBadRequest ", 400)
}

func (o *DeletePublicIPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePublicIPUnauthorized creates a DeletePublicIPUnauthorized with default headers values
func NewDeletePublicIPUnauthorized() *DeletePublicIPUnauthorized {
	return &DeletePublicIPUnauthorized{}
}

/*DeletePublicIPUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type DeletePublicIPUnauthorized struct {
}

func (o *DeletePublicIPUnauthorized) Error() string {
	return fmt.Sprintf("[POST /DeletePublicIp][%d] deletePublicIpUnauthorized ", 401)
}

func (o *DeletePublicIPUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePublicIPInternalServerError creates a DeletePublicIPInternalServerError with default headers values
func NewDeletePublicIPInternalServerError() *DeletePublicIPInternalServerError {
	return &DeletePublicIPInternalServerError{}
}

/*DeletePublicIPInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type DeletePublicIPInternalServerError struct {
}

func (o *DeletePublicIPInternalServerError) Error() string {
	return fmt.Sprintf("[POST /DeletePublicIp][%d] deletePublicIpInternalServerError ", 500)
}

func (o *DeletePublicIPInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
