// Code generated by go-swagger; DO NOT EDIT.

package public_ip

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadPublicIpsParams creates a new ReadPublicIpsParams object
// with the default values initialized.
func NewReadPublicIpsParams() *ReadPublicIpsParams {

	return &ReadPublicIpsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadPublicIpsParamsWithTimeout creates a new ReadPublicIpsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadPublicIpsParamsWithTimeout(timeout time.Duration) *ReadPublicIpsParams {

	return &ReadPublicIpsParams{

		timeout: timeout,
	}
}

// NewReadPublicIpsParamsWithContext creates a new ReadPublicIpsParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadPublicIpsParamsWithContext(ctx context.Context) *ReadPublicIpsParams {

	return &ReadPublicIpsParams{

		Context: ctx,
	}
}

// NewReadPublicIpsParamsWithHTTPClient creates a new ReadPublicIpsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadPublicIpsParamsWithHTTPClient(client *http.Client) *ReadPublicIpsParams {

	return &ReadPublicIpsParams{
		HTTPClient: client,
	}
}

/*ReadPublicIpsParams contains all the parameters to send to the API endpoint
for the read public ips operation typically these are written to a http.Request
*/
type ReadPublicIpsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read public ips params
func (o *ReadPublicIpsParams) WithTimeout(timeout time.Duration) *ReadPublicIpsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read public ips params
func (o *ReadPublicIpsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read public ips params
func (o *ReadPublicIpsParams) WithContext(ctx context.Context) *ReadPublicIpsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read public ips params
func (o *ReadPublicIpsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read public ips params
func (o *ReadPublicIpsParams) WithHTTPClient(client *http.Client) *ReadPublicIpsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read public ips params
func (o *ReadPublicIpsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReadPublicIpsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
