// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteImageReader is a Reader for the DeleteImage structure.
type DeleteImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteImageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteImageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteImageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteImageOK creates a DeleteImageOK with default headers values
func NewDeleteImageOK() *DeleteImageOK {
	return &DeleteImageOK{}
}

/*DeleteImageOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteImageOK struct {
}

func (o *DeleteImageOK) Error() string {
	return fmt.Sprintf("[POST /DeleteImage][%d] deleteImageOK ", 200)
}

func (o *DeleteImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteImageBadRequest creates a DeleteImageBadRequest with default headers values
func NewDeleteImageBadRequest() *DeleteImageBadRequest {
	return &DeleteImageBadRequest{}
}

/*DeleteImageBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type DeleteImageBadRequest struct {
}

func (o *DeleteImageBadRequest) Error() string {
	return fmt.Sprintf("[POST /DeleteImage][%d] deleteImageBadRequest ", 400)
}

func (o *DeleteImageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteImageUnauthorized creates a DeleteImageUnauthorized with default headers values
func NewDeleteImageUnauthorized() *DeleteImageUnauthorized {
	return &DeleteImageUnauthorized{}
}

/*DeleteImageUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type DeleteImageUnauthorized struct {
}

func (o *DeleteImageUnauthorized) Error() string {
	return fmt.Sprintf("[POST /DeleteImage][%d] deleteImageUnauthorized ", 401)
}

func (o *DeleteImageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteImageInternalServerError creates a DeleteImageInternalServerError with default headers values
func NewDeleteImageInternalServerError() *DeleteImageInternalServerError {
	return &DeleteImageInternalServerError{}
}

/*DeleteImageInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type DeleteImageInternalServerError struct {
}

func (o *DeleteImageInternalServerError) Error() string {
	return fmt.Sprintf("[POST /DeleteImage][%d] deleteImageInternalServerError ", 500)
}

func (o *DeleteImageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
