// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadImagesReader is a Reader for the ReadImages structure.
type ReadImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewReadImagesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewReadImagesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewReadImagesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadImagesOK creates a ReadImagesOK with default headers values
func NewReadImagesOK() *ReadImagesOK {
	return &ReadImagesOK{}
}

/*ReadImagesOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadImagesOK struct {
}

func (o *ReadImagesOK) Error() string {
	return fmt.Sprintf("[POST /ReadImages][%d] readImagesOK ", 200)
}

func (o *ReadImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewReadImagesBadRequest creates a ReadImagesBadRequest with default headers values
func NewReadImagesBadRequest() *ReadImagesBadRequest {
	return &ReadImagesBadRequest{}
}

/*ReadImagesBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type ReadImagesBadRequest struct {
}

func (o *ReadImagesBadRequest) Error() string {
	return fmt.Sprintf("[POST /ReadImages][%d] readImagesBadRequest ", 400)
}

func (o *ReadImagesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewReadImagesUnauthorized creates a ReadImagesUnauthorized with default headers values
func NewReadImagesUnauthorized() *ReadImagesUnauthorized {
	return &ReadImagesUnauthorized{}
}

/*ReadImagesUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type ReadImagesUnauthorized struct {
}

func (o *ReadImagesUnauthorized) Error() string {
	return fmt.Sprintf("[POST /ReadImages][%d] readImagesUnauthorized ", 401)
}

func (o *ReadImagesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewReadImagesInternalServerError creates a ReadImagesInternalServerError with default headers values
func NewReadImagesInternalServerError() *ReadImagesInternalServerError {
	return &ReadImagesInternalServerError{}
}

/*ReadImagesInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type ReadImagesInternalServerError struct {
}

func (o *ReadImagesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /ReadImages][%d] readImagesInternalServerError ", 500)
}

func (o *ReadImagesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
