// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadImageExportTasksParams creates a new ReadImageExportTasksParams object
// with the default values initialized.
func NewReadImageExportTasksParams() *ReadImageExportTasksParams {

	return &ReadImageExportTasksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadImageExportTasksParamsWithTimeout creates a new ReadImageExportTasksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadImageExportTasksParamsWithTimeout(timeout time.Duration) *ReadImageExportTasksParams {

	return &ReadImageExportTasksParams{

		timeout: timeout,
	}
}

// NewReadImageExportTasksParamsWithContext creates a new ReadImageExportTasksParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadImageExportTasksParamsWithContext(ctx context.Context) *ReadImageExportTasksParams {

	return &ReadImageExportTasksParams{

		Context: ctx,
	}
}

// NewReadImageExportTasksParamsWithHTTPClient creates a new ReadImageExportTasksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadImageExportTasksParamsWithHTTPClient(client *http.Client) *ReadImageExportTasksParams {

	return &ReadImageExportTasksParams{
		HTTPClient: client,
	}
}

/*ReadImageExportTasksParams contains all the parameters to send to the API endpoint
for the read image export tasks operation typically these are written to a http.Request
*/
type ReadImageExportTasksParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read image export tasks params
func (o *ReadImageExportTasksParams) WithTimeout(timeout time.Duration) *ReadImageExportTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read image export tasks params
func (o *ReadImageExportTasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read image export tasks params
func (o *ReadImageExportTasksParams) WithContext(ctx context.Context) *ReadImageExportTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read image export tasks params
func (o *ReadImageExportTasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read image export tasks params
func (o *ReadImageExportTasksParams) WithHTTPClient(client *http.Client) *ReadImageExportTasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read image export tasks params
func (o *ReadImageExportTasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReadImageExportTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
