// Code generated by go-swagger; DO NOT EDIT.

package virtual_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteVirtualGatewayReader is a Reader for the DeleteVirtualGateway structure.
type DeleteVirtualGatewayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteVirtualGatewayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteVirtualGatewayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteVirtualGatewayOK creates a DeleteVirtualGatewayOK with default headers values
func NewDeleteVirtualGatewayOK() *DeleteVirtualGatewayOK {
	return &DeleteVirtualGatewayOK{}
}

/*DeleteVirtualGatewayOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteVirtualGatewayOK struct {
}

func (o *DeleteVirtualGatewayOK) Error() string {
	return fmt.Sprintf("[POST /DeleteVirtualGateway][%d] deleteVirtualGatewayOK ", 200)
}

func (o *DeleteVirtualGatewayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
