// Code generated by go-swagger; DO NOT EDIT.

package virtual_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// LinkVirtualGatewayReader is a Reader for the LinkVirtualGateway structure.
type LinkVirtualGatewayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LinkVirtualGatewayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLinkVirtualGatewayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLinkVirtualGatewayOK creates a LinkVirtualGatewayOK with default headers values
func NewLinkVirtualGatewayOK() *LinkVirtualGatewayOK {
	return &LinkVirtualGatewayOK{}
}

/*LinkVirtualGatewayOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type LinkVirtualGatewayOK struct {
}

func (o *LinkVirtualGatewayOK) Error() string {
	return fmt.Sprintf("[POST /LinkVirtualGateway][%d] linkVirtualGatewayOK ", 200)
}

func (o *LinkVirtualGatewayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
