// Code generated by go-swagger; DO NOT EDIT.

package virtual_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateRoutePropagationReader is a Reader for the UpdateRoutePropagation structure.
type UpdateRoutePropagationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateRoutePropagationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateRoutePropagationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateRoutePropagationOK creates a UpdateRoutePropagationOK with default headers values
func NewUpdateRoutePropagationOK() *UpdateRoutePropagationOK {
	return &UpdateRoutePropagationOK{}
}

/*UpdateRoutePropagationOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type UpdateRoutePropagationOK struct {
}

func (o *UpdateRoutePropagationOK) Error() string {
	return fmt.Sprintf("[POST /UpdateRoutePropagation][%d] updateRoutePropagationOK ", 200)
}

func (o *UpdateRoutePropagationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
