// Code generated by go-swagger; DO NOT EDIT.

package direct_link_interface

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteDirectLinkInterfaceReader is a Reader for the DeleteDirectLinkInterface structure.
type DeleteDirectLinkInterfaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDirectLinkInterfaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteDirectLinkInterfaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDirectLinkInterfaceOK creates a DeleteDirectLinkInterfaceOK with default headers values
func NewDeleteDirectLinkInterfaceOK() *DeleteDirectLinkInterfaceOK {
	return &DeleteDirectLinkInterfaceOK{}
}

/*DeleteDirectLinkInterfaceOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteDirectLinkInterfaceOK struct {
}

func (o *DeleteDirectLinkInterfaceOK) Error() string {
	return fmt.Sprintf("[POST /DeleteDirectLinkInterface][%d] deleteDirectLinkInterfaceOK ", 200)
}

func (o *DeleteDirectLinkInterfaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
