// Code generated by go-swagger; DO NOT EDIT.

package direct_link_interface

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadDirectLinkInterfacesReader is a Reader for the ReadDirectLinkInterfaces structure.
type ReadDirectLinkInterfacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadDirectLinkInterfacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadDirectLinkInterfacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadDirectLinkInterfacesOK creates a ReadDirectLinkInterfacesOK with default headers values
func NewReadDirectLinkInterfacesOK() *ReadDirectLinkInterfacesOK {
	return &ReadDirectLinkInterfacesOK{}
}

/*ReadDirectLinkInterfacesOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadDirectLinkInterfacesOK struct {
}

func (o *ReadDirectLinkInterfacesOK) Error() string {
	return fmt.Sprintf("[POST /ReadDirectLinkInterfaces][%d] readDirectLinkInterfacesOK ", 200)
}

func (o *ReadDirectLinkInterfacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
