// Code generated by go-swagger; DO NOT EDIT.

package location

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadLocationsReader is a Reader for the ReadLocations structure.
type ReadLocationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadLocationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadLocationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadLocationsOK creates a ReadLocationsOK with default headers values
func NewReadLocationsOK() *ReadLocationsOK {
	return &ReadLocationsOK{}
}

/*ReadLocationsOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadLocationsOK struct {
}

func (o *ReadLocationsOK) Error() string {
	return fmt.Sprintf("[POST /ReadLocations][%d] readLocationsOK ", 200)
}

func (o *ReadLocationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
