// Code generated by go-swagger; DO NOT EDIT.

package client_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteClientGatewayReader is a Reader for the DeleteClientGateway structure.
type DeleteClientGatewayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteClientGatewayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteClientGatewayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteClientGatewayOK creates a DeleteClientGatewayOK with default headers values
func NewDeleteClientGatewayOK() *DeleteClientGatewayOK {
	return &DeleteClientGatewayOK{}
}

/*DeleteClientGatewayOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteClientGatewayOK struct {
}

func (o *DeleteClientGatewayOK) Error() string {
	return fmt.Sprintf("[POST /DeleteClientGateway][%d] deleteClientGatewayOK ", 200)
}

func (o *DeleteClientGatewayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
