// Code generated by go-swagger; DO NOT EDIT.

package dhcp_option

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteDhcpOptionsReader is a Reader for the DeleteDhcpOptions structure.
type DeleteDhcpOptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDhcpOptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteDhcpOptionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDhcpOptionsOK creates a DeleteDhcpOptionsOK with default headers values
func NewDeleteDhcpOptionsOK() *DeleteDhcpOptionsOK {
	return &DeleteDhcpOptionsOK{}
}

/*DeleteDhcpOptionsOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteDhcpOptionsOK struct {
}

func (o *DeleteDhcpOptionsOK) Error() string {
	return fmt.Sprintf("[POST /DeleteDhcpOptions][%d] deleteDhcpOptionsOK ", 200)
}

func (o *DeleteDhcpOptionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
