// Code generated by go-swagger; DO NOT EDIT.

package dhcp_option

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadDhcpOptionsReader is a Reader for the ReadDhcpOptions structure.
type ReadDhcpOptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadDhcpOptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadDhcpOptionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadDhcpOptionsOK creates a ReadDhcpOptionsOK with default headers values
func NewReadDhcpOptionsOK() *ReadDhcpOptionsOK {
	return &ReadDhcpOptionsOK{}
}

/*ReadDhcpOptionsOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadDhcpOptionsOK struct {
}

func (o *ReadDhcpOptionsOK) Error() string {
	return fmt.Sprintf("[POST /ReadDhcpOptions][%d] readDhcpOptionsOK ", 200)
}

func (o *ReadDhcpOptionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
