// Code generated by go-swagger; DO NOT EDIT.

package internet_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteInternetServiceParams creates a new DeleteInternetServiceParams object
// with the default values initialized.
func NewDeleteInternetServiceParams() *DeleteInternetServiceParams {

	return &DeleteInternetServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteInternetServiceParamsWithTimeout creates a new DeleteInternetServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteInternetServiceParamsWithTimeout(timeout time.Duration) *DeleteInternetServiceParams {

	return &DeleteInternetServiceParams{

		timeout: timeout,
	}
}

// NewDeleteInternetServiceParamsWithContext creates a new DeleteInternetServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteInternetServiceParamsWithContext(ctx context.Context) *DeleteInternetServiceParams {

	return &DeleteInternetServiceParams{

		Context: ctx,
	}
}

// NewDeleteInternetServiceParamsWithHTTPClient creates a new DeleteInternetServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteInternetServiceParamsWithHTTPClient(client *http.Client) *DeleteInternetServiceParams {

	return &DeleteInternetServiceParams{
		HTTPClient: client,
	}
}

/*DeleteInternetServiceParams contains all the parameters to send to the API endpoint
for the delete internet service operation typically these are written to a http.Request
*/
type DeleteInternetServiceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete internet service params
func (o *DeleteInternetServiceParams) WithTimeout(timeout time.Duration) *DeleteInternetServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete internet service params
func (o *DeleteInternetServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete internet service params
func (o *DeleteInternetServiceParams) WithContext(ctx context.Context) *DeleteInternetServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete internet service params
func (o *DeleteInternetServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete internet service params
func (o *DeleteInternetServiceParams) WithHTTPClient(client *http.Client) *DeleteInternetServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete internet service params
func (o *DeleteInternetServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteInternetServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
