// Code generated by go-swagger; DO NOT EDIT.

package internet_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteInternetServiceReader is a Reader for the DeleteInternetService structure.
type DeleteInternetServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteInternetServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteInternetServiceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteInternetServiceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteInternetServiceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteInternetServiceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteInternetServiceOK creates a DeleteInternetServiceOK with default headers values
func NewDeleteInternetServiceOK() *DeleteInternetServiceOK {
	return &DeleteInternetServiceOK{}
}

/*DeleteInternetServiceOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteInternetServiceOK struct {
}

func (o *DeleteInternetServiceOK) Error() string {
	return fmt.Sprintf("[POST /DeleteInternetService][%d] deleteInternetServiceOK ", 200)
}

func (o *DeleteInternetServiceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInternetServiceBadRequest creates a DeleteInternetServiceBadRequest with default headers values
func NewDeleteInternetServiceBadRequest() *DeleteInternetServiceBadRequest {
	return &DeleteInternetServiceBadRequest{}
}

/*DeleteInternetServiceBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type DeleteInternetServiceBadRequest struct {
}

func (o *DeleteInternetServiceBadRequest) Error() string {
	return fmt.Sprintf("[POST /DeleteInternetService][%d] deleteInternetServiceBadRequest ", 400)
}

func (o *DeleteInternetServiceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInternetServiceUnauthorized creates a DeleteInternetServiceUnauthorized with default headers values
func NewDeleteInternetServiceUnauthorized() *DeleteInternetServiceUnauthorized {
	return &DeleteInternetServiceUnauthorized{}
}

/*DeleteInternetServiceUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type DeleteInternetServiceUnauthorized struct {
}

func (o *DeleteInternetServiceUnauthorized) Error() string {
	return fmt.Sprintf("[POST /DeleteInternetService][%d] deleteInternetServiceUnauthorized ", 401)
}

func (o *DeleteInternetServiceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInternetServiceInternalServerError creates a DeleteInternetServiceInternalServerError with default headers values
func NewDeleteInternetServiceInternalServerError() *DeleteInternetServiceInternalServerError {
	return &DeleteInternetServiceInternalServerError{}
}

/*DeleteInternetServiceInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type DeleteInternetServiceInternalServerError struct {
}

func (o *DeleteInternetServiceInternalServerError) Error() string {
	return fmt.Sprintf("[POST /DeleteInternetService][%d] deleteInternetServiceInternalServerError ", 500)
}

func (o *DeleteInternetServiceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
