// Code generated by go-swagger; DO NOT EDIT.

package internet_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UnlinkInternetServiceReader is a Reader for the UnlinkInternetService structure.
type UnlinkInternetServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnlinkInternetServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUnlinkInternetServiceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUnlinkInternetServiceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUnlinkInternetServiceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUnlinkInternetServiceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUnlinkInternetServiceOK creates a UnlinkInternetServiceOK with default headers values
func NewUnlinkInternetServiceOK() *UnlinkInternetServiceOK {
	return &UnlinkInternetServiceOK{}
}

/*UnlinkInternetServiceOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type UnlinkInternetServiceOK struct {
}

func (o *UnlinkInternetServiceOK) Error() string {
	return fmt.Sprintf("[POST /UnlinkInternetService][%d] unlinkInternetServiceOK ", 200)
}

func (o *UnlinkInternetServiceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUnlinkInternetServiceBadRequest creates a UnlinkInternetServiceBadRequest with default headers values
func NewUnlinkInternetServiceBadRequest() *UnlinkInternetServiceBadRequest {
	return &UnlinkInternetServiceBadRequest{}
}

/*UnlinkInternetServiceBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type UnlinkInternetServiceBadRequest struct {
}

func (o *UnlinkInternetServiceBadRequest) Error() string {
	return fmt.Sprintf("[POST /UnlinkInternetService][%d] unlinkInternetServiceBadRequest ", 400)
}

func (o *UnlinkInternetServiceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUnlinkInternetServiceUnauthorized creates a UnlinkInternetServiceUnauthorized with default headers values
func NewUnlinkInternetServiceUnauthorized() *UnlinkInternetServiceUnauthorized {
	return &UnlinkInternetServiceUnauthorized{}
}

/*UnlinkInternetServiceUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type UnlinkInternetServiceUnauthorized struct {
}

func (o *UnlinkInternetServiceUnauthorized) Error() string {
	return fmt.Sprintf("[POST /UnlinkInternetService][%d] unlinkInternetServiceUnauthorized ", 401)
}

func (o *UnlinkInternetServiceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUnlinkInternetServiceInternalServerError creates a UnlinkInternetServiceInternalServerError with default headers values
func NewUnlinkInternetServiceInternalServerError() *UnlinkInternetServiceInternalServerError {
	return &UnlinkInternetServiceInternalServerError{}
}

/*UnlinkInternetServiceInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type UnlinkInternetServiceInternalServerError struct {
}

func (o *UnlinkInternetServiceInternalServerError) Error() string {
	return fmt.Sprintf("[POST /UnlinkInternetService][%d] unlinkInternetServiceInternalServerError ", 500)
}

func (o *UnlinkInternetServiceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
