// Code generated by go-swagger; DO NOT EDIT.

package nic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteNicParams creates a new DeleteNicParams object
// with the default values initialized.
func NewDeleteNicParams() *DeleteNicParams {

	return &DeleteNicParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteNicParamsWithTimeout creates a new DeleteNicParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteNicParamsWithTimeout(timeout time.Duration) *DeleteNicParams {

	return &DeleteNicParams{

		timeout: timeout,
	}
}

// NewDeleteNicParamsWithContext creates a new DeleteNicParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteNicParamsWithContext(ctx context.Context) *DeleteNicParams {

	return &DeleteNicParams{

		Context: ctx,
	}
}

// NewDeleteNicParamsWithHTTPClient creates a new DeleteNicParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteNicParamsWithHTTPClient(client *http.Client) *DeleteNicParams {

	return &DeleteNicParams{
		HTTPClient: client,
	}
}

/*DeleteNicParams contains all the parameters to send to the API endpoint
for the delete nic operation typically these are written to a http.Request
*/
type DeleteNicParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete nic params
func (o *DeleteNicParams) WithTimeout(timeout time.Duration) *DeleteNicParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete nic params
func (o *DeleteNicParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete nic params
func (o *DeleteNicParams) WithContext(ctx context.Context) *DeleteNicParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete nic params
func (o *DeleteNicParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete nic params
func (o *DeleteNicParams) WithHTTPClient(client *http.Client) *DeleteNicParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete nic params
func (o *DeleteNicParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteNicParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
