// Code generated by go-swagger; DO NOT EDIT.

package nic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadNicsParams creates a new ReadNicsParams object
// with the default values initialized.
func NewReadNicsParams() *ReadNicsParams {

	return &ReadNicsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadNicsParamsWithTimeout creates a new ReadNicsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadNicsParamsWithTimeout(timeout time.Duration) *ReadNicsParams {

	return &ReadNicsParams{

		timeout: timeout,
	}
}

// NewReadNicsParamsWithContext creates a new ReadNicsParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadNicsParamsWithContext(ctx context.Context) *ReadNicsParams {

	return &ReadNicsParams{

		Context: ctx,
	}
}

// NewReadNicsParamsWithHTTPClient creates a new ReadNicsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadNicsParamsWithHTTPClient(client *http.Client) *ReadNicsParams {

	return &ReadNicsParams{
		HTTPClient: client,
	}
}

/*ReadNicsParams contains all the parameters to send to the API endpoint
for the read nics operation typically these are written to a http.Request
*/
type ReadNicsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read nics params
func (o *ReadNicsParams) WithTimeout(timeout time.Duration) *ReadNicsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read nics params
func (o *ReadNicsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read nics params
func (o *ReadNicsParams) WithContext(ctx context.Context) *ReadNicsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read nics params
func (o *ReadNicsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read nics params
func (o *ReadNicsParams) WithHTTPClient(client *http.Client) *ReadNicsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read nics params
func (o *ReadNicsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReadNicsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
