// Code generated by go-swagger; DO NOT EDIT.

package direct_link

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDirectLinkParams creates a new DeleteDirectLinkParams object
// with the default values initialized.
func NewDeleteDirectLinkParams() *DeleteDirectLinkParams {

	return &DeleteDirectLinkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDirectLinkParamsWithTimeout creates a new DeleteDirectLinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDirectLinkParamsWithTimeout(timeout time.Duration) *DeleteDirectLinkParams {

	return &DeleteDirectLinkParams{

		timeout: timeout,
	}
}

// NewDeleteDirectLinkParamsWithContext creates a new DeleteDirectLinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDirectLinkParamsWithContext(ctx context.Context) *DeleteDirectLinkParams {

	return &DeleteDirectLinkParams{

		Context: ctx,
	}
}

// NewDeleteDirectLinkParamsWithHTTPClient creates a new DeleteDirectLinkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDirectLinkParamsWithHTTPClient(client *http.Client) *DeleteDirectLinkParams {

	return &DeleteDirectLinkParams{
		HTTPClient: client,
	}
}

/*DeleteDirectLinkParams contains all the parameters to send to the API endpoint
for the delete direct link operation typically these are written to a http.Request
*/
type DeleteDirectLinkParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete direct link params
func (o *DeleteDirectLinkParams) WithTimeout(timeout time.Duration) *DeleteDirectLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete direct link params
func (o *DeleteDirectLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete direct link params
func (o *DeleteDirectLinkParams) WithContext(ctx context.Context) *DeleteDirectLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete direct link params
func (o *DeleteDirectLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete direct link params
func (o *DeleteDirectLinkParams) WithHTTPClient(client *http.Client) *DeleteDirectLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete direct link params
func (o *DeleteDirectLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDirectLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
