// Code generated by go-swagger; DO NOT EDIT.

package api_log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadAPILogsReader is a Reader for the ReadAPILogs structure.
type ReadAPILogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadAPILogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadAPILogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadAPILogsOK creates a ReadAPILogsOK with default headers values
func NewReadAPILogsOK() *ReadAPILogsOK {
	return &ReadAPILogsOK{}
}

/*ReadAPILogsOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadAPILogsOK struct {
}

func (o *ReadAPILogsOK) Error() string {
	return fmt.Sprintf("[POST /ReadApiLogs][%d] readApiLogsOK ", 200)
}

func (o *ReadAPILogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
