// Code generated by go-swagger; DO NOT EDIT.

package product_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadProductTypesReader is a Reader for the ReadProductTypes structure.
type ReadProductTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadProductTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadProductTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadProductTypesOK creates a ReadProductTypesOK with default headers values
func NewReadProductTypesOK() *ReadProductTypesOK {
	return &ReadProductTypesOK{}
}

/*ReadProductTypesOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadProductTypesOK struct {
}

func (o *ReadProductTypesOK) Error() string {
	return fmt.Sprintf("[POST /ReadProductTypes][%d] readProductTypesOK ", 200)
}

func (o *ReadProductTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
