// Code generated by go-swagger; DO NOT EDIT.

package snapshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadSnapshotExportTasksReader is a Reader for the ReadSnapshotExportTasks structure.
type ReadSnapshotExportTasksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadSnapshotExportTasksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadSnapshotExportTasksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadSnapshotExportTasksOK creates a ReadSnapshotExportTasksOK with default headers values
func NewReadSnapshotExportTasksOK() *ReadSnapshotExportTasksOK {
	return &ReadSnapshotExportTasksOK{}
}

/*ReadSnapshotExportTasksOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadSnapshotExportTasksOK struct {
}

func (o *ReadSnapshotExportTasksOK) Error() string {
	return fmt.Sprintf("[POST /ReadSnapshotExportTasks][%d] readSnapshotExportTasksOK ", 200)
}

func (o *ReadSnapshotExportTasksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
