// Code generated by go-swagger; DO NOT EDIT.

package net_peering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAcceptNetPeeringParams creates a new AcceptNetPeeringParams object
// with the default values initialized.
func NewAcceptNetPeeringParams() *AcceptNetPeeringParams {

	return &AcceptNetPeeringParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAcceptNetPeeringParamsWithTimeout creates a new AcceptNetPeeringParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAcceptNetPeeringParamsWithTimeout(timeout time.Duration) *AcceptNetPeeringParams {

	return &AcceptNetPeeringParams{

		timeout: timeout,
	}
}

// NewAcceptNetPeeringParamsWithContext creates a new AcceptNetPeeringParams object
// with the default values initialized, and the ability to set a context for a request
func NewAcceptNetPeeringParamsWithContext(ctx context.Context) *AcceptNetPeeringParams {

	return &AcceptNetPeeringParams{

		Context: ctx,
	}
}

// NewAcceptNetPeeringParamsWithHTTPClient creates a new AcceptNetPeeringParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAcceptNetPeeringParamsWithHTTPClient(client *http.Client) *AcceptNetPeeringParams {

	return &AcceptNetPeeringParams{
		HTTPClient: client,
	}
}

/*AcceptNetPeeringParams contains all the parameters to send to the API endpoint
for the accept net peering operation typically these are written to a http.Request
*/
type AcceptNetPeeringParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the accept net peering params
func (o *AcceptNetPeeringParams) WithTimeout(timeout time.Duration) *AcceptNetPeeringParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the accept net peering params
func (o *AcceptNetPeeringParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the accept net peering params
func (o *AcceptNetPeeringParams) WithContext(ctx context.Context) *AcceptNetPeeringParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the accept net peering params
func (o *AcceptNetPeeringParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the accept net peering params
func (o *AcceptNetPeeringParams) WithHTTPClient(client *http.Client) *AcceptNetPeeringParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the accept net peering params
func (o *AcceptNetPeeringParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AcceptNetPeeringParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
