// Code generated by go-swagger; DO NOT EDIT.

package net_peering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRejectNetPeeringParams creates a new RejectNetPeeringParams object
// with the default values initialized.
func NewRejectNetPeeringParams() *RejectNetPeeringParams {

	return &RejectNetPeeringParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRejectNetPeeringParamsWithTimeout creates a new RejectNetPeeringParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRejectNetPeeringParamsWithTimeout(timeout time.Duration) *RejectNetPeeringParams {

	return &RejectNetPeeringParams{

		timeout: timeout,
	}
}

// NewRejectNetPeeringParamsWithContext creates a new RejectNetPeeringParams object
// with the default values initialized, and the ability to set a context for a request
func NewRejectNetPeeringParamsWithContext(ctx context.Context) *RejectNetPeeringParams {

	return &RejectNetPeeringParams{

		Context: ctx,
	}
}

// NewRejectNetPeeringParamsWithHTTPClient creates a new RejectNetPeeringParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRejectNetPeeringParamsWithHTTPClient(client *http.Client) *RejectNetPeeringParams {

	return &RejectNetPeeringParams{
		HTTPClient: client,
	}
}

/*RejectNetPeeringParams contains all the parameters to send to the API endpoint
for the reject net peering operation typically these are written to a http.Request
*/
type RejectNetPeeringParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the reject net peering params
func (o *RejectNetPeeringParams) WithTimeout(timeout time.Duration) *RejectNetPeeringParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reject net peering params
func (o *RejectNetPeeringParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reject net peering params
func (o *RejectNetPeeringParams) WithContext(ctx context.Context) *RejectNetPeeringParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reject net peering params
func (o *RejectNetPeeringParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reject net peering params
func (o *RejectNetPeeringParams) WithHTTPClient(client *http.Client) *RejectNetPeeringParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reject net peering params
func (o *RejectNetPeeringParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RejectNetPeeringParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
