// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteExportTaskParams creates a new DeleteExportTaskParams object
// with the default values initialized.
func NewDeleteExportTaskParams() *DeleteExportTaskParams {

	return &DeleteExportTaskParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteExportTaskParamsWithTimeout creates a new DeleteExportTaskParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteExportTaskParamsWithTimeout(timeout time.Duration) *DeleteExportTaskParams {

	return &DeleteExportTaskParams{

		timeout: timeout,
	}
}

// NewDeleteExportTaskParamsWithContext creates a new DeleteExportTaskParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteExportTaskParamsWithContext(ctx context.Context) *DeleteExportTaskParams {

	return &DeleteExportTaskParams{

		Context: ctx,
	}
}

// NewDeleteExportTaskParamsWithHTTPClient creates a new DeleteExportTaskParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteExportTaskParamsWithHTTPClient(client *http.Client) *DeleteExportTaskParams {

	return &DeleteExportTaskParams{
		HTTPClient: client,
	}
}

/*DeleteExportTaskParams contains all the parameters to send to the API endpoint
for the delete export task operation typically these are written to a http.Request
*/
type DeleteExportTaskParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete export task params
func (o *DeleteExportTaskParams) WithTimeout(timeout time.Duration) *DeleteExportTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete export task params
func (o *DeleteExportTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete export task params
func (o *DeleteExportTaskParams) WithContext(ctx context.Context) *DeleteExportTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete export task params
func (o *DeleteExportTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete export task params
func (o *DeleteExportTaskParams) WithHTTPClient(client *http.Client) *DeleteExportTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete export task params
func (o *DeleteExportTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteExportTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
