// Code generated by go-swagger; DO NOT EDIT.

package subnet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSubnetParams creates a new DeleteSubnetParams object
// with the default values initialized.
func NewDeleteSubnetParams() *DeleteSubnetParams {

	return &DeleteSubnetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSubnetParamsWithTimeout creates a new DeleteSubnetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSubnetParamsWithTimeout(timeout time.Duration) *DeleteSubnetParams {

	return &DeleteSubnetParams{

		timeout: timeout,
	}
}

// NewDeleteSubnetParamsWithContext creates a new DeleteSubnetParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSubnetParamsWithContext(ctx context.Context) *DeleteSubnetParams {

	return &DeleteSubnetParams{

		Context: ctx,
	}
}

// NewDeleteSubnetParamsWithHTTPClient creates a new DeleteSubnetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSubnetParamsWithHTTPClient(client *http.Client) *DeleteSubnetParams {

	return &DeleteSubnetParams{
		HTTPClient: client,
	}
}

/*DeleteSubnetParams contains all the parameters to send to the API endpoint
for the delete subnet operation typically these are written to a http.Request
*/
type DeleteSubnetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete subnet params
func (o *DeleteSubnetParams) WithTimeout(timeout time.Duration) *DeleteSubnetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete subnet params
func (o *DeleteSubnetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete subnet params
func (o *DeleteSubnetParams) WithContext(ctx context.Context) *DeleteSubnetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete subnet params
func (o *DeleteSubnetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete subnet params
func (o *DeleteSubnetParams) WithHTTPClient(client *http.Client) *DeleteSubnetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete subnet params
func (o *DeleteSubnetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSubnetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
