// Code generated by go-swagger; DO NOT EDIT.

package subnet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadSubnetsParams creates a new ReadSubnetsParams object
// with the default values initialized.
func NewReadSubnetsParams() *ReadSubnetsParams {

	return &ReadSubnetsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadSubnetsParamsWithTimeout creates a new ReadSubnetsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadSubnetsParamsWithTimeout(timeout time.Duration) *ReadSubnetsParams {

	return &ReadSubnetsParams{

		timeout: timeout,
	}
}

// NewReadSubnetsParamsWithContext creates a new ReadSubnetsParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadSubnetsParamsWithContext(ctx context.Context) *ReadSubnetsParams {

	return &ReadSubnetsParams{

		Context: ctx,
	}
}

// NewReadSubnetsParamsWithHTTPClient creates a new ReadSubnetsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadSubnetsParamsWithHTTPClient(client *http.Client) *ReadSubnetsParams {

	return &ReadSubnetsParams{
		HTTPClient: client,
	}
}

/*ReadSubnetsParams contains all the parameters to send to the API endpoint
for the read subnets operation typically these are written to a http.Request
*/
type ReadSubnetsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read subnets params
func (o *ReadSubnetsParams) WithTimeout(timeout time.Duration) *ReadSubnetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read subnets params
func (o *ReadSubnetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read subnets params
func (o *ReadSubnetsParams) WithContext(ctx context.Context) *ReadSubnetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read subnets params
func (o *ReadSubnetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read subnets params
func (o *ReadSubnetsParams) WithHTTPClient(client *http.Client) *ReadSubnetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read subnets params
func (o *ReadSubnetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReadSubnetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
