// Code generated by go-swagger; DO NOT EDIT.

package public_ip_range

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadPublicIPRangesReader is a Reader for the ReadPublicIPRanges structure.
type ReadPublicIPRangesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadPublicIPRangesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadPublicIPRangesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadPublicIPRangesOK creates a ReadPublicIPRangesOK with default headers values
func NewReadPublicIPRangesOK() *ReadPublicIPRangesOK {
	return &ReadPublicIPRangesOK{}
}

/*ReadPublicIPRangesOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadPublicIPRangesOK struct {
}

func (o *ReadPublicIPRangesOK) Error() string {
	return fmt.Sprintf("[POST /ReadPublicIpRanges][%d] readPublicIpRangesOK ", 200)
}

func (o *ReadPublicIPRangesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
