// Code generated by go-swagger; DO NOT EDIT.

package subregion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadSubregionsParams creates a new ReadSubregionsParams object
// with the default values initialized.
func NewReadSubregionsParams() *ReadSubregionsParams {

	return &ReadSubregionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadSubregionsParamsWithTimeout creates a new ReadSubregionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadSubregionsParamsWithTimeout(timeout time.Duration) *ReadSubregionsParams {

	return &ReadSubregionsParams{

		timeout: timeout,
	}
}

// NewReadSubregionsParamsWithContext creates a new ReadSubregionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadSubregionsParamsWithContext(ctx context.Context) *ReadSubregionsParams {

	return &ReadSubregionsParams{

		Context: ctx,
	}
}

// NewReadSubregionsParamsWithHTTPClient creates a new ReadSubregionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadSubregionsParamsWithHTTPClient(client *http.Client) *ReadSubregionsParams {

	return &ReadSubregionsParams{
		HTTPClient: client,
	}
}

/*ReadSubregionsParams contains all the parameters to send to the API endpoint
for the read subregions operation typically these are written to a http.Request
*/
type ReadSubregionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read subregions params
func (o *ReadSubregionsParams) WithTimeout(timeout time.Duration) *ReadSubregionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read subregions params
func (o *ReadSubregionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read subregions params
func (o *ReadSubregionsParams) WithContext(ctx context.Context) *ReadSubregionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read subregions params
func (o *ReadSubregionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read subregions params
func (o *ReadSubregionsParams) WithHTTPClient(client *http.Client) *ReadSubregionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read subregions params
func (o *ReadSubregionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReadSubregionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
