// Code generated by go-swagger; DO NOT EDIT.

package route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateRouteReader is a Reader for the CreateRoute structure.
type CreateRouteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRouteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateRouteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateRouteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateRouteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateRouteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateRouteOK creates a CreateRouteOK with default headers values
func NewCreateRouteOK() *CreateRouteOK {
	return &CreateRouteOK{}
}

/*CreateRouteOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreateRouteOK struct {
}

func (o *CreateRouteOK) Error() string {
	return fmt.Sprintf("[POST /CreateRoute][%d] createRouteOK ", 200)
}

func (o *CreateRouteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRouteBadRequest creates a CreateRouteBadRequest with default headers values
func NewCreateRouteBadRequest() *CreateRouteBadRequest {
	return &CreateRouteBadRequest{}
}

/*CreateRouteBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type CreateRouteBadRequest struct {
}

func (o *CreateRouteBadRequest) Error() string {
	return fmt.Sprintf("[POST /CreateRoute][%d] createRouteBadRequest ", 400)
}

func (o *CreateRouteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRouteUnauthorized creates a CreateRouteUnauthorized with default headers values
func NewCreateRouteUnauthorized() *CreateRouteUnauthorized {
	return &CreateRouteUnauthorized{}
}

/*CreateRouteUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type CreateRouteUnauthorized struct {
}

func (o *CreateRouteUnauthorized) Error() string {
	return fmt.Sprintf("[POST /CreateRoute][%d] createRouteUnauthorized ", 401)
}

func (o *CreateRouteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRouteInternalServerError creates a CreateRouteInternalServerError with default headers values
func NewCreateRouteInternalServerError() *CreateRouteInternalServerError {
	return &CreateRouteInternalServerError{}
}

/*CreateRouteInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type CreateRouteInternalServerError struct {
}

func (o *CreateRouteInternalServerError) Error() string {
	return fmt.Sprintf("[POST /CreateRoute][%d] createRouteInternalServerError ", 500)
}

func (o *CreateRouteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
