// Code generated by go-swagger; DO NOT EDIT.

package route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateRouteParams creates a new UpdateRouteParams object
// with the default values initialized.
func NewUpdateRouteParams() *UpdateRouteParams {

	return &UpdateRouteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRouteParamsWithTimeout creates a new UpdateRouteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRouteParamsWithTimeout(timeout time.Duration) *UpdateRouteParams {

	return &UpdateRouteParams{

		timeout: timeout,
	}
}

// NewUpdateRouteParamsWithContext creates a new UpdateRouteParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRouteParamsWithContext(ctx context.Context) *UpdateRouteParams {

	return &UpdateRouteParams{

		Context: ctx,
	}
}

// NewUpdateRouteParamsWithHTTPClient creates a new UpdateRouteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRouteParamsWithHTTPClient(client *http.Client) *UpdateRouteParams {

	return &UpdateRouteParams{
		HTTPClient: client,
	}
}

/*UpdateRouteParams contains all the parameters to send to the API endpoint
for the update route operation typically these are written to a http.Request
*/
type UpdateRouteParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update route params
func (o *UpdateRouteParams) WithTimeout(timeout time.Duration) *UpdateRouteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update route params
func (o *UpdateRouteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update route params
func (o *UpdateRouteParams) WithContext(ctx context.Context) *UpdateRouteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update route params
func (o *UpdateRouteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update route params
func (o *UpdateRouteParams) WithHTTPClient(client *http.Client) *UpdateRouteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update route params
func (o *UpdateRouteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRouteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
