// Code generated by go-swagger; DO NOT EDIT.

package nat_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteNatServiceParams creates a new DeleteNatServiceParams object
// with the default values initialized.
func NewDeleteNatServiceParams() *DeleteNatServiceParams {

	return &DeleteNatServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteNatServiceParamsWithTimeout creates a new DeleteNatServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteNatServiceParamsWithTimeout(timeout time.Duration) *DeleteNatServiceParams {

	return &DeleteNatServiceParams{

		timeout: timeout,
	}
}

// NewDeleteNatServiceParamsWithContext creates a new DeleteNatServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteNatServiceParamsWithContext(ctx context.Context) *DeleteNatServiceParams {

	return &DeleteNatServiceParams{

		Context: ctx,
	}
}

// NewDeleteNatServiceParamsWithHTTPClient creates a new DeleteNatServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteNatServiceParamsWithHTTPClient(client *http.Client) *DeleteNatServiceParams {

	return &DeleteNatServiceParams{
		HTTPClient: client,
	}
}

/*DeleteNatServiceParams contains all the parameters to send to the API endpoint
for the delete nat service operation typically these are written to a http.Request
*/
type DeleteNatServiceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete nat service params
func (o *DeleteNatServiceParams) WithTimeout(timeout time.Duration) *DeleteNatServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete nat service params
func (o *DeleteNatServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete nat service params
func (o *DeleteNatServiceParams) WithContext(ctx context.Context) *DeleteNatServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete nat service params
func (o *DeleteNatServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete nat service params
func (o *DeleteNatServiceParams) WithHTTPClient(client *http.Client) *DeleteNatServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete nat service params
func (o *DeleteNatServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteNatServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
