// Code generated by go-swagger; DO NOT EDIT.

package nat_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadNatServicesParams creates a new ReadNatServicesParams object
// with the default values initialized.
func NewReadNatServicesParams() *ReadNatServicesParams {

	return &ReadNatServicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadNatServicesParamsWithTimeout creates a new ReadNatServicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadNatServicesParamsWithTimeout(timeout time.Duration) *ReadNatServicesParams {

	return &ReadNatServicesParams{

		timeout: timeout,
	}
}

// NewReadNatServicesParamsWithContext creates a new ReadNatServicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadNatServicesParamsWithContext(ctx context.Context) *ReadNatServicesParams {

	return &ReadNatServicesParams{

		Context: ctx,
	}
}

// NewReadNatServicesParamsWithHTTPClient creates a new ReadNatServicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadNatServicesParamsWithHTTPClient(client *http.Client) *ReadNatServicesParams {

	return &ReadNatServicesParams{
		HTTPClient: client,
	}
}

/*ReadNatServicesParams contains all the parameters to send to the API endpoint
for the read nat services operation typically these are written to a http.Request
*/
type ReadNatServicesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read nat services params
func (o *ReadNatServicesParams) WithTimeout(timeout time.Duration) *ReadNatServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read nat services params
func (o *ReadNatServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read nat services params
func (o *ReadNatServicesParams) WithContext(ctx context.Context) *ReadNatServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read nat services params
func (o *ReadNatServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read nat services params
func (o *ReadNatServicesParams) WithHTTPClient(client *http.Client) *ReadNatServicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read nat services params
func (o *ReadNatServicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReadNatServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
