// Code generated by go-swagger; DO NOT EDIT.

package load_balancer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteLoadBalancerParams creates a new DeleteLoadBalancerParams object
// with the default values initialized.
func NewDeleteLoadBalancerParams() *DeleteLoadBalancerParams {

	return &DeleteLoadBalancerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLoadBalancerParamsWithTimeout creates a new DeleteLoadBalancerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteLoadBalancerParamsWithTimeout(timeout time.Duration) *DeleteLoadBalancerParams {

	return &DeleteLoadBalancerParams{

		timeout: timeout,
	}
}

// NewDeleteLoadBalancerParamsWithContext creates a new DeleteLoadBalancerParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteLoadBalancerParamsWithContext(ctx context.Context) *DeleteLoadBalancerParams {

	return &DeleteLoadBalancerParams{

		Context: ctx,
	}
}

// NewDeleteLoadBalancerParamsWithHTTPClient creates a new DeleteLoadBalancerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteLoadBalancerParamsWithHTTPClient(client *http.Client) *DeleteLoadBalancerParams {

	return &DeleteLoadBalancerParams{
		HTTPClient: client,
	}
}

/*DeleteLoadBalancerParams contains all the parameters to send to the API endpoint
for the delete load balancer operation typically these are written to a http.Request
*/
type DeleteLoadBalancerParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete load balancer params
func (o *DeleteLoadBalancerParams) WithTimeout(timeout time.Duration) *DeleteLoadBalancerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete load balancer params
func (o *DeleteLoadBalancerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete load balancer params
func (o *DeleteLoadBalancerParams) WithContext(ctx context.Context) *DeleteLoadBalancerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete load balancer params
func (o *DeleteLoadBalancerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete load balancer params
func (o *DeleteLoadBalancerParams) WithHTTPClient(client *http.Client) *DeleteLoadBalancerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete load balancer params
func (o *DeleteLoadBalancerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLoadBalancerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
