// Code generated by go-swagger; DO NOT EDIT.

package load_balancer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadLoadBalancersParams creates a new ReadLoadBalancersParams object
// with the default values initialized.
func NewReadLoadBalancersParams() *ReadLoadBalancersParams {

	return &ReadLoadBalancersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadLoadBalancersParamsWithTimeout creates a new ReadLoadBalancersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadLoadBalancersParamsWithTimeout(timeout time.Duration) *ReadLoadBalancersParams {

	return &ReadLoadBalancersParams{

		timeout: timeout,
	}
}

// NewReadLoadBalancersParamsWithContext creates a new ReadLoadBalancersParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadLoadBalancersParamsWithContext(ctx context.Context) *ReadLoadBalancersParams {

	return &ReadLoadBalancersParams{

		Context: ctx,
	}
}

// NewReadLoadBalancersParamsWithHTTPClient creates a new ReadLoadBalancersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadLoadBalancersParamsWithHTTPClient(client *http.Client) *ReadLoadBalancersParams {

	return &ReadLoadBalancersParams{
		HTTPClient: client,
	}
}

/*ReadLoadBalancersParams contains all the parameters to send to the API endpoint
for the read load balancers operation typically these are written to a http.Request
*/
type ReadLoadBalancersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read load balancers params
func (o *ReadLoadBalancersParams) WithTimeout(timeout time.Duration) *ReadLoadBalancersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read load balancers params
func (o *ReadLoadBalancersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read load balancers params
func (o *ReadLoadBalancersParams) WithContext(ctx context.Context) *ReadLoadBalancersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read load balancers params
func (o *ReadLoadBalancersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read load balancers params
func (o *ReadLoadBalancersParams) WithHTTPClient(client *http.Client) *ReadLoadBalancersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read load balancers params
func (o *ReadLoadBalancersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReadLoadBalancersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
