// Code generated by go-swagger; DO NOT EDIT.

package load_balancer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateLoadBalancerParams creates a new UpdateLoadBalancerParams object
// with the default values initialized.
func NewUpdateLoadBalancerParams() *UpdateLoadBalancerParams {

	return &UpdateLoadBalancerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateLoadBalancerParamsWithTimeout creates a new UpdateLoadBalancerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateLoadBalancerParamsWithTimeout(timeout time.Duration) *UpdateLoadBalancerParams {

	return &UpdateLoadBalancerParams{

		timeout: timeout,
	}
}

// NewUpdateLoadBalancerParamsWithContext creates a new UpdateLoadBalancerParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateLoadBalancerParamsWithContext(ctx context.Context) *UpdateLoadBalancerParams {

	return &UpdateLoadBalancerParams{

		Context: ctx,
	}
}

// NewUpdateLoadBalancerParamsWithHTTPClient creates a new UpdateLoadBalancerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateLoadBalancerParamsWithHTTPClient(client *http.Client) *UpdateLoadBalancerParams {

	return &UpdateLoadBalancerParams{
		HTTPClient: client,
	}
}

/*UpdateLoadBalancerParams contains all the parameters to send to the API endpoint
for the update load balancer operation typically these are written to a http.Request
*/
type UpdateLoadBalancerParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update load balancer params
func (o *UpdateLoadBalancerParams) WithTimeout(timeout time.Duration) *UpdateLoadBalancerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update load balancer params
func (o *UpdateLoadBalancerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update load balancer params
func (o *UpdateLoadBalancerParams) WithContext(ctx context.Context) *UpdateLoadBalancerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update load balancer params
func (o *UpdateLoadBalancerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update load balancer params
func (o *UpdateLoadBalancerParams) WithHTTPClient(client *http.Client) *UpdateLoadBalancerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update load balancer params
func (o *UpdateLoadBalancerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateLoadBalancerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
