// Code generated by go-swagger; DO NOT EDIT.

package security_group_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateSecurityGroupRuleParams creates a new CreateSecurityGroupRuleParams object
// with the default values initialized.
func NewCreateSecurityGroupRuleParams() *CreateSecurityGroupRuleParams {

	return &CreateSecurityGroupRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSecurityGroupRuleParamsWithTimeout creates a new CreateSecurityGroupRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSecurityGroupRuleParamsWithTimeout(timeout time.Duration) *CreateSecurityGroupRuleParams {

	return &CreateSecurityGroupRuleParams{

		timeout: timeout,
	}
}

// NewCreateSecurityGroupRuleParamsWithContext creates a new CreateSecurityGroupRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateSecurityGroupRuleParamsWithContext(ctx context.Context) *CreateSecurityGroupRuleParams {

	return &CreateSecurityGroupRuleParams{

		Context: ctx,
	}
}

// NewCreateSecurityGroupRuleParamsWithHTTPClient creates a new CreateSecurityGroupRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateSecurityGroupRuleParamsWithHTTPClient(client *http.Client) *CreateSecurityGroupRuleParams {

	return &CreateSecurityGroupRuleParams{
		HTTPClient: client,
	}
}

/*CreateSecurityGroupRuleParams contains all the parameters to send to the API endpoint
for the create security group rule operation typically these are written to a http.Request
*/
type CreateSecurityGroupRuleParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create security group rule params
func (o *CreateSecurityGroupRuleParams) WithTimeout(timeout time.Duration) *CreateSecurityGroupRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create security group rule params
func (o *CreateSecurityGroupRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create security group rule params
func (o *CreateSecurityGroupRuleParams) WithContext(ctx context.Context) *CreateSecurityGroupRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create security group rule params
func (o *CreateSecurityGroupRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create security group rule params
func (o *CreateSecurityGroupRuleParams) WithHTTPClient(client *http.Client) *CreateSecurityGroupRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create security group rule params
func (o *CreateSecurityGroupRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSecurityGroupRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
