// Code generated by go-swagger; DO NOT EDIT.

package security_group_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateSecurityGroupRuleReader is a Reader for the CreateSecurityGroupRule structure.
type CreateSecurityGroupRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSecurityGroupRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateSecurityGroupRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateSecurityGroupRuleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateSecurityGroupRuleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateSecurityGroupRuleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateSecurityGroupRuleOK creates a CreateSecurityGroupRuleOK with default headers values
func NewCreateSecurityGroupRuleOK() *CreateSecurityGroupRuleOK {
	return &CreateSecurityGroupRuleOK{}
}

/*CreateSecurityGroupRuleOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreateSecurityGroupRuleOK struct {
}

func (o *CreateSecurityGroupRuleOK) Error() string {
	return fmt.Sprintf("[POST /CreateSecurityGroupRule][%d] createSecurityGroupRuleOK ", 200)
}

func (o *CreateSecurityGroupRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSecurityGroupRuleBadRequest creates a CreateSecurityGroupRuleBadRequest with default headers values
func NewCreateSecurityGroupRuleBadRequest() *CreateSecurityGroupRuleBadRequest {
	return &CreateSecurityGroupRuleBadRequest{}
}

/*CreateSecurityGroupRuleBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type CreateSecurityGroupRuleBadRequest struct {
}

func (o *CreateSecurityGroupRuleBadRequest) Error() string {
	return fmt.Sprintf("[POST /CreateSecurityGroupRule][%d] createSecurityGroupRuleBadRequest ", 400)
}

func (o *CreateSecurityGroupRuleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSecurityGroupRuleUnauthorized creates a CreateSecurityGroupRuleUnauthorized with default headers values
func NewCreateSecurityGroupRuleUnauthorized() *CreateSecurityGroupRuleUnauthorized {
	return &CreateSecurityGroupRuleUnauthorized{}
}

/*CreateSecurityGroupRuleUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type CreateSecurityGroupRuleUnauthorized struct {
}

func (o *CreateSecurityGroupRuleUnauthorized) Error() string {
	return fmt.Sprintf("[POST /CreateSecurityGroupRule][%d] createSecurityGroupRuleUnauthorized ", 401)
}

func (o *CreateSecurityGroupRuleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSecurityGroupRuleInternalServerError creates a CreateSecurityGroupRuleInternalServerError with default headers values
func NewCreateSecurityGroupRuleInternalServerError() *CreateSecurityGroupRuleInternalServerError {
	return &CreateSecurityGroupRuleInternalServerError{}
}

/*CreateSecurityGroupRuleInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type CreateSecurityGroupRuleInternalServerError struct {
}

func (o *CreateSecurityGroupRuleInternalServerError) Error() string {
	return fmt.Sprintf("[POST /CreateSecurityGroupRule][%d] createSecurityGroupRuleInternalServerError ", 500)
}

func (o *CreateSecurityGroupRuleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
