// Code generated by go-swagger; DO NOT EDIT.

package listener

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateLoadBalancerListenersReader is a Reader for the CreateLoadBalancerListeners structure.
type CreateLoadBalancerListenersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateLoadBalancerListenersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateLoadBalancerListenersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateLoadBalancerListenersOK creates a CreateLoadBalancerListenersOK with default headers values
func NewCreateLoadBalancerListenersOK() *CreateLoadBalancerListenersOK {
	return &CreateLoadBalancerListenersOK{}
}

/*CreateLoadBalancerListenersOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreateLoadBalancerListenersOK struct {
}

func (o *CreateLoadBalancerListenersOK) Error() string {
	return fmt.Sprintf("[POST /CreateLoadBalancerListeners][%d] createLoadBalancerListenersOK ", 200)
}

func (o *CreateLoadBalancerListenersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
