// Code generated by go-swagger; DO NOT EDIT.

package listener

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateLoadBalancerListenersParams creates a new CreateLoadBalancerListenersParams object
// with the default values initialized.
func NewCreateLoadBalancerListenersParams() *CreateLoadBalancerListenersParams {

	return &CreateLoadBalancerListenersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateLoadBalancerListenersParamsWithTimeout creates a new CreateLoadBalancerListenersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateLoadBalancerListenersParamsWithTimeout(timeout time.Duration) *CreateLoadBalancerListenersParams {

	return &CreateLoadBalancerListenersParams{

		timeout: timeout,
	}
}

// NewCreateLoadBalancerListenersParamsWithContext creates a new CreateLoadBalancerListenersParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateLoadBalancerListenersParamsWithContext(ctx context.Context) *CreateLoadBalancerListenersParams {

	return &CreateLoadBalancerListenersParams{

		Context: ctx,
	}
}

// NewCreateLoadBalancerListenersParamsWithHTTPClient creates a new CreateLoadBalancerListenersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateLoadBalancerListenersParamsWithHTTPClient(client *http.Client) *CreateLoadBalancerListenersParams {

	return &CreateLoadBalancerListenersParams{
		HTTPClient: client,
	}
}

/*CreateLoadBalancerListenersParams contains all the parameters to send to the API endpoint
for the create load balancer listeners operation typically these are written to a http.Request
*/
type CreateLoadBalancerListenersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create load balancer listeners params
func (o *CreateLoadBalancerListenersParams) WithTimeout(timeout time.Duration) *CreateLoadBalancerListenersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create load balancer listeners params
func (o *CreateLoadBalancerListenersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create load balancer listeners params
func (o *CreateLoadBalancerListenersParams) WithContext(ctx context.Context) *CreateLoadBalancerListenersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create load balancer listeners params
func (o *CreateLoadBalancerListenersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create load balancer listeners params
func (o *CreateLoadBalancerListenersParams) WithHTTPClient(client *http.Client) *CreateLoadBalancerListenersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create load balancer listeners params
func (o *CreateLoadBalancerListenersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreateLoadBalancerListenersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
