// Code generated by go-swagger; DO NOT EDIT.

package listener

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteLoadBalancerListenersReader is a Reader for the DeleteLoadBalancerListeners structure.
type DeleteLoadBalancerListenersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLoadBalancerListenersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteLoadBalancerListenersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteLoadBalancerListenersOK creates a DeleteLoadBalancerListenersOK with default headers values
func NewDeleteLoadBalancerListenersOK() *DeleteLoadBalancerListenersOK {
	return &DeleteLoadBalancerListenersOK{}
}

/*DeleteLoadBalancerListenersOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteLoadBalancerListenersOK struct {
}

func (o *DeleteLoadBalancerListenersOK) Error() string {
	return fmt.Sprintf("[POST /DeleteLoadBalancerListeners][%d] deleteLoadBalancerListenersOK ", 200)
}

func (o *DeleteLoadBalancerListenersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
