// Code generated by go-swagger; DO NOT EDIT.

package listener

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new listener API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for listener API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreateLoadBalancerListeners create load balancer listeners API
*/
func (a *Client) CreateLoadBalancerListeners(params *CreateLoadBalancerListenersParams, authInfo runtime.ClientAuthInfoWriter) (*CreateLoadBalancerListenersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateLoadBalancerListenersParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "CreateLoadBalancerListeners",
		Method:             "POST",
		PathPattern:        "/CreateLoadBalancerListeners",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateLoadBalancerListenersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateLoadBalancerListenersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateLoadBalancerListeners: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteLoadBalancerListeners delete load balancer listeners API
*/
func (a *Client) DeleteLoadBalancerListeners(params *DeleteLoadBalancerListenersParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteLoadBalancerListenersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteLoadBalancerListenersParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DeleteLoadBalancerListeners",
		Method:             "POST",
		PathPattern:        "/DeleteLoadBalancerListeners",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteLoadBalancerListenersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteLoadBalancerListenersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteLoadBalancerListeners: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
