// Code generated by go-swagger; DO NOT EDIT.

package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateVolumeReader is a Reader for the CreateVolume structure.
type CreateVolumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateVolumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateVolumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateVolumeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateVolumeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateVolumeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateVolumeOK creates a CreateVolumeOK with default headers values
func NewCreateVolumeOK() *CreateVolumeOK {
	return &CreateVolumeOK{}
}

/*CreateVolumeOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreateVolumeOK struct {
}

func (o *CreateVolumeOK) Error() string {
	return fmt.Sprintf("[POST /CreateVolume][%d] createVolumeOK ", 200)
}

func (o *CreateVolumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateVolumeBadRequest creates a CreateVolumeBadRequest with default headers values
func NewCreateVolumeBadRequest() *CreateVolumeBadRequest {
	return &CreateVolumeBadRequest{}
}

/*CreateVolumeBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type CreateVolumeBadRequest struct {
}

func (o *CreateVolumeBadRequest) Error() string {
	return fmt.Sprintf("[POST /CreateVolume][%d] createVolumeBadRequest ", 400)
}

func (o *CreateVolumeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateVolumeUnauthorized creates a CreateVolumeUnauthorized with default headers values
func NewCreateVolumeUnauthorized() *CreateVolumeUnauthorized {
	return &CreateVolumeUnauthorized{}
}

/*CreateVolumeUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type CreateVolumeUnauthorized struct {
}

func (o *CreateVolumeUnauthorized) Error() string {
	return fmt.Sprintf("[POST /CreateVolume][%d] createVolumeUnauthorized ", 401)
}

func (o *CreateVolumeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateVolumeInternalServerError creates a CreateVolumeInternalServerError with default headers values
func NewCreateVolumeInternalServerError() *CreateVolumeInternalServerError {
	return &CreateVolumeInternalServerError{}
}

/*CreateVolumeInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type CreateVolumeInternalServerError struct {
}

func (o *CreateVolumeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /CreateVolume][%d] createVolumeInternalServerError ", 500)
}

func (o *CreateVolumeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
