// Code generated by go-swagger; DO NOT EDIT.

package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteVolumeReader is a Reader for the DeleteVolume structure.
type DeleteVolumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteVolumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteVolumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteVolumeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteVolumeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteVolumeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteVolumeOK creates a DeleteVolumeOK with default headers values
func NewDeleteVolumeOK() *DeleteVolumeOK {
	return &DeleteVolumeOK{}
}

/*DeleteVolumeOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteVolumeOK struct {
}

func (o *DeleteVolumeOK) Error() string {
	return fmt.Sprintf("[POST /DeleteVolume][%d] deleteVolumeOK ", 200)
}

func (o *DeleteVolumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteVolumeBadRequest creates a DeleteVolumeBadRequest with default headers values
func NewDeleteVolumeBadRequest() *DeleteVolumeBadRequest {
	return &DeleteVolumeBadRequest{}
}

/*DeleteVolumeBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type DeleteVolumeBadRequest struct {
}

func (o *DeleteVolumeBadRequest) Error() string {
	return fmt.Sprintf("[POST /DeleteVolume][%d] deleteVolumeBadRequest ", 400)
}

func (o *DeleteVolumeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteVolumeUnauthorized creates a DeleteVolumeUnauthorized with default headers values
func NewDeleteVolumeUnauthorized() *DeleteVolumeUnauthorized {
	return &DeleteVolumeUnauthorized{}
}

/*DeleteVolumeUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type DeleteVolumeUnauthorized struct {
}

func (o *DeleteVolumeUnauthorized) Error() string {
	return fmt.Sprintf("[POST /DeleteVolume][%d] deleteVolumeUnauthorized ", 401)
}

func (o *DeleteVolumeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteVolumeInternalServerError creates a DeleteVolumeInternalServerError with default headers values
func NewDeleteVolumeInternalServerError() *DeleteVolumeInternalServerError {
	return &DeleteVolumeInternalServerError{}
}

/*DeleteVolumeInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type DeleteVolumeInternalServerError struct {
}

func (o *DeleteVolumeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /DeleteVolume][%d] deleteVolumeInternalServerError ", 500)
}

func (o *DeleteVolumeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
