// Code generated by go-swagger; DO NOT EDIT.

package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUnlinkVolumeParams creates a new UnlinkVolumeParams object
// with the default values initialized.
func NewUnlinkVolumeParams() *UnlinkVolumeParams {

	return &UnlinkVolumeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUnlinkVolumeParamsWithTimeout creates a new UnlinkVolumeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUnlinkVolumeParamsWithTimeout(timeout time.Duration) *UnlinkVolumeParams {

	return &UnlinkVolumeParams{

		timeout: timeout,
	}
}

// NewUnlinkVolumeParamsWithContext creates a new UnlinkVolumeParams object
// with the default values initialized, and the ability to set a context for a request
func NewUnlinkVolumeParamsWithContext(ctx context.Context) *UnlinkVolumeParams {

	return &UnlinkVolumeParams{

		Context: ctx,
	}
}

// NewUnlinkVolumeParamsWithHTTPClient creates a new UnlinkVolumeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUnlinkVolumeParamsWithHTTPClient(client *http.Client) *UnlinkVolumeParams {

	return &UnlinkVolumeParams{
		HTTPClient: client,
	}
}

/*UnlinkVolumeParams contains all the parameters to send to the API endpoint
for the unlink volume operation typically these are written to a http.Request
*/
type UnlinkVolumeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the unlink volume params
func (o *UnlinkVolumeParams) WithTimeout(timeout time.Duration) *UnlinkVolumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unlink volume params
func (o *UnlinkVolumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unlink volume params
func (o *UnlinkVolumeParams) WithContext(ctx context.Context) *UnlinkVolumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unlink volume params
func (o *UnlinkVolumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unlink volume params
func (o *UnlinkVolumeParams) WithHTTPClient(client *http.Client) *UnlinkVolumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unlink volume params
func (o *UnlinkVolumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UnlinkVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
