// Code generated by go-swagger; DO NOT EDIT.

package load_balancer_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateLoadBalancerPolicyReader is a Reader for the CreateLoadBalancerPolicy structure.
type CreateLoadBalancerPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateLoadBalancerPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateLoadBalancerPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateLoadBalancerPolicyOK creates a CreateLoadBalancerPolicyOK with default headers values
func NewCreateLoadBalancerPolicyOK() *CreateLoadBalancerPolicyOK {
	return &CreateLoadBalancerPolicyOK{}
}

/*CreateLoadBalancerPolicyOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreateLoadBalancerPolicyOK struct {
}

func (o *CreateLoadBalancerPolicyOK) Error() string {
	return fmt.Sprintf("[POST /CreateLoadBalancerPolicy][%d] createLoadBalancerPolicyOK ", 200)
}

func (o *CreateLoadBalancerPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
