// Code generated by go-swagger; DO NOT EDIT.

package load_balancer_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteLoadBalancerPolicyReader is a Reader for the DeleteLoadBalancerPolicy structure.
type DeleteLoadBalancerPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLoadBalancerPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteLoadBalancerPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteLoadBalancerPolicyOK creates a DeleteLoadBalancerPolicyOK with default headers values
func NewDeleteLoadBalancerPolicyOK() *DeleteLoadBalancerPolicyOK {
	return &DeleteLoadBalancerPolicyOK{}
}

/*DeleteLoadBalancerPolicyOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteLoadBalancerPolicyOK struct {
}

func (o *DeleteLoadBalancerPolicyOK) Error() string {
	return fmt.Sprintf("[POST /DeleteLoadBalancerPolicy][%d] deleteLoadBalancerPolicyOK ", 200)
}

func (o *DeleteLoadBalancerPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
