// Code generated by go-swagger; DO NOT EDIT.

package load_balancer_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteLoadBalancerPolicyParams creates a new DeleteLoadBalancerPolicyParams object
// with the default values initialized.
func NewDeleteLoadBalancerPolicyParams() *DeleteLoadBalancerPolicyParams {

	return &DeleteLoadBalancerPolicyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLoadBalancerPolicyParamsWithTimeout creates a new DeleteLoadBalancerPolicyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteLoadBalancerPolicyParamsWithTimeout(timeout time.Duration) *DeleteLoadBalancerPolicyParams {

	return &DeleteLoadBalancerPolicyParams{

		timeout: timeout,
	}
}

// NewDeleteLoadBalancerPolicyParamsWithContext creates a new DeleteLoadBalancerPolicyParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteLoadBalancerPolicyParamsWithContext(ctx context.Context) *DeleteLoadBalancerPolicyParams {

	return &DeleteLoadBalancerPolicyParams{

		Context: ctx,
	}
}

// NewDeleteLoadBalancerPolicyParamsWithHTTPClient creates a new DeleteLoadBalancerPolicyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteLoadBalancerPolicyParamsWithHTTPClient(client *http.Client) *DeleteLoadBalancerPolicyParams {

	return &DeleteLoadBalancerPolicyParams{
		HTTPClient: client,
	}
}

/*DeleteLoadBalancerPolicyParams contains all the parameters to send to the API endpoint
for the delete load balancer policy operation typically these are written to a http.Request
*/
type DeleteLoadBalancerPolicyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete load balancer policy params
func (o *DeleteLoadBalancerPolicyParams) WithTimeout(timeout time.Duration) *DeleteLoadBalancerPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete load balancer policy params
func (o *DeleteLoadBalancerPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete load balancer policy params
func (o *DeleteLoadBalancerPolicyParams) WithContext(ctx context.Context) *DeleteLoadBalancerPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete load balancer policy params
func (o *DeleteLoadBalancerPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete load balancer policy params
func (o *DeleteLoadBalancerPolicyParams) WithHTTPClient(client *http.Client) *DeleteLoadBalancerPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete load balancer policy params
func (o *DeleteLoadBalancerPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLoadBalancerPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
