// Code generated by go-swagger; DO NOT EDIT.

package load_balancer_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new load balancer policy API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for load balancer policy API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreateLoadBalancerPolicy create load balancer policy API
*/
func (a *Client) CreateLoadBalancerPolicy(params *CreateLoadBalancerPolicyParams, authInfo runtime.ClientAuthInfoWriter) (*CreateLoadBalancerPolicyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateLoadBalancerPolicyParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "CreateLoadBalancerPolicy",
		Method:             "POST",
		PathPattern:        "/CreateLoadBalancerPolicy",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateLoadBalancerPolicyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateLoadBalancerPolicyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateLoadBalancerPolicy: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteLoadBalancerPolicy delete load balancer policy API
*/
func (a *Client) DeleteLoadBalancerPolicy(params *DeleteLoadBalancerPolicyParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteLoadBalancerPolicyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteLoadBalancerPolicyParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DeleteLoadBalancerPolicy",
		Method:             "POST",
		PathPattern:        "/DeleteLoadBalancerPolicy",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteLoadBalancerPolicyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteLoadBalancerPolicyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteLoadBalancerPolicy: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
