// Code generated by go-swagger; DO NOT EDIT.

package flexible_gpu

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateFlexibleGpuParams creates a new CreateFlexibleGpuParams object
// with the default values initialized.
func NewCreateFlexibleGpuParams() *CreateFlexibleGpuParams {

	return &CreateFlexibleGpuParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateFlexibleGpuParamsWithTimeout creates a new CreateFlexibleGpuParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateFlexibleGpuParamsWithTimeout(timeout time.Duration) *CreateFlexibleGpuParams {

	return &CreateFlexibleGpuParams{

		timeout: timeout,
	}
}

// NewCreateFlexibleGpuParamsWithContext creates a new CreateFlexibleGpuParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateFlexibleGpuParamsWithContext(ctx context.Context) *CreateFlexibleGpuParams {

	return &CreateFlexibleGpuParams{

		Context: ctx,
	}
}

// NewCreateFlexibleGpuParamsWithHTTPClient creates a new CreateFlexibleGpuParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateFlexibleGpuParamsWithHTTPClient(client *http.Client) *CreateFlexibleGpuParams {

	return &CreateFlexibleGpuParams{
		HTTPClient: client,
	}
}

/*CreateFlexibleGpuParams contains all the parameters to send to the API endpoint
for the create flexible gpu operation typically these are written to a http.Request
*/
type CreateFlexibleGpuParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create flexible gpu params
func (o *CreateFlexibleGpuParams) WithTimeout(timeout time.Duration) *CreateFlexibleGpuParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create flexible gpu params
func (o *CreateFlexibleGpuParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create flexible gpu params
func (o *CreateFlexibleGpuParams) WithContext(ctx context.Context) *CreateFlexibleGpuParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create flexible gpu params
func (o *CreateFlexibleGpuParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create flexible gpu params
func (o *CreateFlexibleGpuParams) WithHTTPClient(client *http.Client) *CreateFlexibleGpuParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create flexible gpu params
func (o *CreateFlexibleGpuParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreateFlexibleGpuParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
