// Code generated by go-swagger; DO NOT EDIT.

package flexible_gpu

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteFlexibleGpuParams creates a new DeleteFlexibleGpuParams object
// with the default values initialized.
func NewDeleteFlexibleGpuParams() *DeleteFlexibleGpuParams {

	return &DeleteFlexibleGpuParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFlexibleGpuParamsWithTimeout creates a new DeleteFlexibleGpuParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFlexibleGpuParamsWithTimeout(timeout time.Duration) *DeleteFlexibleGpuParams {

	return &DeleteFlexibleGpuParams{

		timeout: timeout,
	}
}

// NewDeleteFlexibleGpuParamsWithContext creates a new DeleteFlexibleGpuParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFlexibleGpuParamsWithContext(ctx context.Context) *DeleteFlexibleGpuParams {

	return &DeleteFlexibleGpuParams{

		Context: ctx,
	}
}

// NewDeleteFlexibleGpuParamsWithHTTPClient creates a new DeleteFlexibleGpuParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFlexibleGpuParamsWithHTTPClient(client *http.Client) *DeleteFlexibleGpuParams {

	return &DeleteFlexibleGpuParams{
		HTTPClient: client,
	}
}

/*DeleteFlexibleGpuParams contains all the parameters to send to the API endpoint
for the delete flexible gpu operation typically these are written to a http.Request
*/
type DeleteFlexibleGpuParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete flexible gpu params
func (o *DeleteFlexibleGpuParams) WithTimeout(timeout time.Duration) *DeleteFlexibleGpuParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete flexible gpu params
func (o *DeleteFlexibleGpuParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete flexible gpu params
func (o *DeleteFlexibleGpuParams) WithContext(ctx context.Context) *DeleteFlexibleGpuParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete flexible gpu params
func (o *DeleteFlexibleGpuParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete flexible gpu params
func (o *DeleteFlexibleGpuParams) WithHTTPClient(client *http.Client) *DeleteFlexibleGpuParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete flexible gpu params
func (o *DeleteFlexibleGpuParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFlexibleGpuParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
