// Code generated by go-swagger; DO NOT EDIT.

package flexible_gpu

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLinkFlexibleGpuParams creates a new LinkFlexibleGpuParams object
// with the default values initialized.
func NewLinkFlexibleGpuParams() *LinkFlexibleGpuParams {

	return &LinkFlexibleGpuParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLinkFlexibleGpuParamsWithTimeout creates a new LinkFlexibleGpuParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLinkFlexibleGpuParamsWithTimeout(timeout time.Duration) *LinkFlexibleGpuParams {

	return &LinkFlexibleGpuParams{

		timeout: timeout,
	}
}

// NewLinkFlexibleGpuParamsWithContext creates a new LinkFlexibleGpuParams object
// with the default values initialized, and the ability to set a context for a request
func NewLinkFlexibleGpuParamsWithContext(ctx context.Context) *LinkFlexibleGpuParams {

	return &LinkFlexibleGpuParams{

		Context: ctx,
	}
}

// NewLinkFlexibleGpuParamsWithHTTPClient creates a new LinkFlexibleGpuParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLinkFlexibleGpuParamsWithHTTPClient(client *http.Client) *LinkFlexibleGpuParams {

	return &LinkFlexibleGpuParams{
		HTTPClient: client,
	}
}

/*LinkFlexibleGpuParams contains all the parameters to send to the API endpoint
for the link flexible gpu operation typically these are written to a http.Request
*/
type LinkFlexibleGpuParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the link flexible gpu params
func (o *LinkFlexibleGpuParams) WithTimeout(timeout time.Duration) *LinkFlexibleGpuParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the link flexible gpu params
func (o *LinkFlexibleGpuParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the link flexible gpu params
func (o *LinkFlexibleGpuParams) WithContext(ctx context.Context) *LinkFlexibleGpuParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the link flexible gpu params
func (o *LinkFlexibleGpuParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the link flexible gpu params
func (o *LinkFlexibleGpuParams) WithHTTPClient(client *http.Client) *LinkFlexibleGpuParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the link flexible gpu params
func (o *LinkFlexibleGpuParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *LinkFlexibleGpuParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
