// Code generated by go-swagger; DO NOT EDIT.

package flexible_gpu

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// LinkFlexibleGpuReader is a Reader for the LinkFlexibleGpu structure.
type LinkFlexibleGpuReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LinkFlexibleGpuReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLinkFlexibleGpuOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLinkFlexibleGpuOK creates a LinkFlexibleGpuOK with default headers values
func NewLinkFlexibleGpuOK() *LinkFlexibleGpuOK {
	return &LinkFlexibleGpuOK{}
}

/*LinkFlexibleGpuOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type LinkFlexibleGpuOK struct {
}

func (o *LinkFlexibleGpuOK) Error() string {
	return fmt.Sprintf("[POST /LinkFlexibleGpu][%d] linkFlexibleGpuOK ", 200)
}

func (o *LinkFlexibleGpuOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
