// Code generated by go-swagger; DO NOT EDIT.

package flexible_gpu

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadFlexibleGpusParams creates a new ReadFlexibleGpusParams object
// with the default values initialized.
func NewReadFlexibleGpusParams() *ReadFlexibleGpusParams {

	return &ReadFlexibleGpusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadFlexibleGpusParamsWithTimeout creates a new ReadFlexibleGpusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadFlexibleGpusParamsWithTimeout(timeout time.Duration) *ReadFlexibleGpusParams {

	return &ReadFlexibleGpusParams{

		timeout: timeout,
	}
}

// NewReadFlexibleGpusParamsWithContext creates a new ReadFlexibleGpusParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadFlexibleGpusParamsWithContext(ctx context.Context) *ReadFlexibleGpusParams {

	return &ReadFlexibleGpusParams{

		Context: ctx,
	}
}

// NewReadFlexibleGpusParamsWithHTTPClient creates a new ReadFlexibleGpusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadFlexibleGpusParamsWithHTTPClient(client *http.Client) *ReadFlexibleGpusParams {

	return &ReadFlexibleGpusParams{
		HTTPClient: client,
	}
}

/*ReadFlexibleGpusParams contains all the parameters to send to the API endpoint
for the read flexible gpus operation typically these are written to a http.Request
*/
type ReadFlexibleGpusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read flexible gpus params
func (o *ReadFlexibleGpusParams) WithTimeout(timeout time.Duration) *ReadFlexibleGpusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read flexible gpus params
func (o *ReadFlexibleGpusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read flexible gpus params
func (o *ReadFlexibleGpusParams) WithContext(ctx context.Context) *ReadFlexibleGpusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read flexible gpus params
func (o *ReadFlexibleGpusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read flexible gpus params
func (o *ReadFlexibleGpusParams) WithHTTPClient(client *http.Client) *ReadFlexibleGpusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read flexible gpus params
func (o *ReadFlexibleGpusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReadFlexibleGpusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
