// Code generated by go-swagger; DO NOT EDIT.

package flexible_gpu

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadFlexibleGpuCatalogParams creates a new ReadFlexibleGpuCatalogParams object
// with the default values initialized.
func NewReadFlexibleGpuCatalogParams() *ReadFlexibleGpuCatalogParams {

	return &ReadFlexibleGpuCatalogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadFlexibleGpuCatalogParamsWithTimeout creates a new ReadFlexibleGpuCatalogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadFlexibleGpuCatalogParamsWithTimeout(timeout time.Duration) *ReadFlexibleGpuCatalogParams {

	return &ReadFlexibleGpuCatalogParams{

		timeout: timeout,
	}
}

// NewReadFlexibleGpuCatalogParamsWithContext creates a new ReadFlexibleGpuCatalogParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadFlexibleGpuCatalogParamsWithContext(ctx context.Context) *ReadFlexibleGpuCatalogParams {

	return &ReadFlexibleGpuCatalogParams{

		Context: ctx,
	}
}

// NewReadFlexibleGpuCatalogParamsWithHTTPClient creates a new ReadFlexibleGpuCatalogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadFlexibleGpuCatalogParamsWithHTTPClient(client *http.Client) *ReadFlexibleGpuCatalogParams {

	return &ReadFlexibleGpuCatalogParams{
		HTTPClient: client,
	}
}

/*ReadFlexibleGpuCatalogParams contains all the parameters to send to the API endpoint
for the read flexible gpu catalog operation typically these are written to a http.Request
*/
type ReadFlexibleGpuCatalogParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read flexible gpu catalog params
func (o *ReadFlexibleGpuCatalogParams) WithTimeout(timeout time.Duration) *ReadFlexibleGpuCatalogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read flexible gpu catalog params
func (o *ReadFlexibleGpuCatalogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read flexible gpu catalog params
func (o *ReadFlexibleGpuCatalogParams) WithContext(ctx context.Context) *ReadFlexibleGpuCatalogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read flexible gpu catalog params
func (o *ReadFlexibleGpuCatalogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read flexible gpu catalog params
func (o *ReadFlexibleGpuCatalogParams) WithHTTPClient(client *http.Client) *ReadFlexibleGpuCatalogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read flexible gpu catalog params
func (o *ReadFlexibleGpuCatalogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReadFlexibleGpuCatalogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
