// Code generated by go-swagger; DO NOT EDIT.

package flexible_gpu

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadFlexibleGpusReader is a Reader for the ReadFlexibleGpus structure.
type ReadFlexibleGpusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadFlexibleGpusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadFlexibleGpusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadFlexibleGpusOK creates a ReadFlexibleGpusOK with default headers values
func NewReadFlexibleGpusOK() *ReadFlexibleGpusOK {
	return &ReadFlexibleGpusOK{}
}

/*ReadFlexibleGpusOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadFlexibleGpusOK struct {
}

func (o *ReadFlexibleGpusOK) Error() string {
	return fmt.Sprintf("[POST /ReadFlexibleGpus][%d] readFlexibleGpusOK ", 200)
}

func (o *ReadFlexibleGpusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
