// Code generated by go-swagger; DO NOT EDIT.

package flexible_gpu

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UnlinkFlexibleGpuReader is a Reader for the UnlinkFlexibleGpu structure.
type UnlinkFlexibleGpuReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnlinkFlexibleGpuReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUnlinkFlexibleGpuOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUnlinkFlexibleGpuOK creates a UnlinkFlexibleGpuOK with default headers values
func NewUnlinkFlexibleGpuOK() *UnlinkFlexibleGpuOK {
	return &UnlinkFlexibleGpuOK{}
}

/*UnlinkFlexibleGpuOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type UnlinkFlexibleGpuOK struct {
}

func (o *UnlinkFlexibleGpuOK) Error() string {
	return fmt.Sprintf("[POST /UnlinkFlexibleGpu][%d] unlinkFlexibleGpuOK ", 200)
}

func (o *UnlinkFlexibleGpuOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
