// Code generated by go-swagger; DO NOT EDIT.

package flexible_gpu

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateFlexibleGpuReader is a Reader for the UpdateFlexibleGpu structure.
type UpdateFlexibleGpuReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateFlexibleGpuReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateFlexibleGpuOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateFlexibleGpuOK creates a UpdateFlexibleGpuOK with default headers values
func NewUpdateFlexibleGpuOK() *UpdateFlexibleGpuOK {
	return &UpdateFlexibleGpuOK{}
}

/*UpdateFlexibleGpuOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type UpdateFlexibleGpuOK struct {
}

func (o *UpdateFlexibleGpuOK) Error() string {
	return fmt.Sprintf("[POST /UpdateFlexibleGpu][%d] updateFlexibleGpuOK ", 200)
}

func (o *UpdateFlexibleGpuOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
