// Code generated by go-swagger; DO NOT EDIT.

package flexible_gpu

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateFlexibleGpuParams creates a new UpdateFlexibleGpuParams object
// with the default values initialized.
func NewUpdateFlexibleGpuParams() *UpdateFlexibleGpuParams {

	return &UpdateFlexibleGpuParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateFlexibleGpuParamsWithTimeout creates a new UpdateFlexibleGpuParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateFlexibleGpuParamsWithTimeout(timeout time.Duration) *UpdateFlexibleGpuParams {

	return &UpdateFlexibleGpuParams{

		timeout: timeout,
	}
}

// NewUpdateFlexibleGpuParamsWithContext creates a new UpdateFlexibleGpuParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateFlexibleGpuParamsWithContext(ctx context.Context) *UpdateFlexibleGpuParams {

	return &UpdateFlexibleGpuParams{

		Context: ctx,
	}
}

// NewUpdateFlexibleGpuParamsWithHTTPClient creates a new UpdateFlexibleGpuParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateFlexibleGpuParamsWithHTTPClient(client *http.Client) *UpdateFlexibleGpuParams {

	return &UpdateFlexibleGpuParams{
		HTTPClient: client,
	}
}

/*UpdateFlexibleGpuParams contains all the parameters to send to the API endpoint
for the update flexible gpu operation typically these are written to a http.Request
*/
type UpdateFlexibleGpuParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update flexible gpu params
func (o *UpdateFlexibleGpuParams) WithTimeout(timeout time.Duration) *UpdateFlexibleGpuParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update flexible gpu params
func (o *UpdateFlexibleGpuParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update flexible gpu params
func (o *UpdateFlexibleGpuParams) WithContext(ctx context.Context) *UpdateFlexibleGpuParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update flexible gpu params
func (o *UpdateFlexibleGpuParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update flexible gpu params
func (o *UpdateFlexibleGpuParams) WithHTTPClient(client *http.Client) *UpdateFlexibleGpuParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update flexible gpu params
func (o *UpdateFlexibleGpuParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateFlexibleGpuParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
