// Code generated by go-swagger; DO NOT EDIT.

package vpn_connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateVpnConnectionReader is a Reader for the CreateVpnConnection structure.
type CreateVpnConnectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateVpnConnectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateVpnConnectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateVpnConnectionOK creates a CreateVpnConnectionOK with default headers values
func NewCreateVpnConnectionOK() *CreateVpnConnectionOK {
	return &CreateVpnConnectionOK{}
}

/*CreateVpnConnectionOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreateVpnConnectionOK struct {
}

func (o *CreateVpnConnectionOK) Error() string {
	return fmt.Sprintf("[POST /CreateVpnConnection][%d] createVpnConnectionOK ", 200)
}

func (o *CreateVpnConnectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
