// Code generated by go-swagger; DO NOT EDIT.

package vpn_connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateVpnConnectionRouteParams creates a new CreateVpnConnectionRouteParams object
// with the default values initialized.
func NewCreateVpnConnectionRouteParams() *CreateVpnConnectionRouteParams {

	return &CreateVpnConnectionRouteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateVpnConnectionRouteParamsWithTimeout creates a new CreateVpnConnectionRouteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateVpnConnectionRouteParamsWithTimeout(timeout time.Duration) *CreateVpnConnectionRouteParams {

	return &CreateVpnConnectionRouteParams{

		timeout: timeout,
	}
}

// NewCreateVpnConnectionRouteParamsWithContext creates a new CreateVpnConnectionRouteParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateVpnConnectionRouteParamsWithContext(ctx context.Context) *CreateVpnConnectionRouteParams {

	return &CreateVpnConnectionRouteParams{

		Context: ctx,
	}
}

// NewCreateVpnConnectionRouteParamsWithHTTPClient creates a new CreateVpnConnectionRouteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateVpnConnectionRouteParamsWithHTTPClient(client *http.Client) *CreateVpnConnectionRouteParams {

	return &CreateVpnConnectionRouteParams{
		HTTPClient: client,
	}
}

/*CreateVpnConnectionRouteParams contains all the parameters to send to the API endpoint
for the create vpn connection route operation typically these are written to a http.Request
*/
type CreateVpnConnectionRouteParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create vpn connection route params
func (o *CreateVpnConnectionRouteParams) WithTimeout(timeout time.Duration) *CreateVpnConnectionRouteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create vpn connection route params
func (o *CreateVpnConnectionRouteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create vpn connection route params
func (o *CreateVpnConnectionRouteParams) WithContext(ctx context.Context) *CreateVpnConnectionRouteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create vpn connection route params
func (o *CreateVpnConnectionRouteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create vpn connection route params
func (o *CreateVpnConnectionRouteParams) WithHTTPClient(client *http.Client) *CreateVpnConnectionRouteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create vpn connection route params
func (o *CreateVpnConnectionRouteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreateVpnConnectionRouteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
