// Code generated by go-swagger; DO NOT EDIT.

package vpn_connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateVpnConnectionRouteReader is a Reader for the CreateVpnConnectionRoute structure.
type CreateVpnConnectionRouteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateVpnConnectionRouteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateVpnConnectionRouteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateVpnConnectionRouteOK creates a CreateVpnConnectionRouteOK with default headers values
func NewCreateVpnConnectionRouteOK() *CreateVpnConnectionRouteOK {
	return &CreateVpnConnectionRouteOK{}
}

/*CreateVpnConnectionRouteOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreateVpnConnectionRouteOK struct {
}

func (o *CreateVpnConnectionRouteOK) Error() string {
	return fmt.Sprintf("[POST /CreateVpnConnectionRoute][%d] createVpnConnectionRouteOK ", 200)
}

func (o *CreateVpnConnectionRouteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
