// Code generated by go-swagger; DO NOT EDIT.

package vpn_connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateVpnConnectionParams creates a new CreateVpnConnectionParams object
// with the default values initialized.
func NewCreateVpnConnectionParams() *CreateVpnConnectionParams {

	return &CreateVpnConnectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateVpnConnectionParamsWithTimeout creates a new CreateVpnConnectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateVpnConnectionParamsWithTimeout(timeout time.Duration) *CreateVpnConnectionParams {

	return &CreateVpnConnectionParams{

		timeout: timeout,
	}
}

// NewCreateVpnConnectionParamsWithContext creates a new CreateVpnConnectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateVpnConnectionParamsWithContext(ctx context.Context) *CreateVpnConnectionParams {

	return &CreateVpnConnectionParams{

		Context: ctx,
	}
}

// NewCreateVpnConnectionParamsWithHTTPClient creates a new CreateVpnConnectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateVpnConnectionParamsWithHTTPClient(client *http.Client) *CreateVpnConnectionParams {

	return &CreateVpnConnectionParams{
		HTTPClient: client,
	}
}

/*CreateVpnConnectionParams contains all the parameters to send to the API endpoint
for the create vpn connection operation typically these are written to a http.Request
*/
type CreateVpnConnectionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create vpn connection params
func (o *CreateVpnConnectionParams) WithTimeout(timeout time.Duration) *CreateVpnConnectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create vpn connection params
func (o *CreateVpnConnectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create vpn connection params
func (o *CreateVpnConnectionParams) WithContext(ctx context.Context) *CreateVpnConnectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create vpn connection params
func (o *CreateVpnConnectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create vpn connection params
func (o *CreateVpnConnectionParams) WithHTTPClient(client *http.Client) *CreateVpnConnectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create vpn connection params
func (o *CreateVpnConnectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreateVpnConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
