// Code generated by go-swagger; DO NOT EDIT.

package vpn_connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteVpnConnectionRouteReader is a Reader for the DeleteVpnConnectionRoute structure.
type DeleteVpnConnectionRouteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteVpnConnectionRouteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteVpnConnectionRouteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteVpnConnectionRouteOK creates a DeleteVpnConnectionRouteOK with default headers values
func NewDeleteVpnConnectionRouteOK() *DeleteVpnConnectionRouteOK {
	return &DeleteVpnConnectionRouteOK{}
}

/*DeleteVpnConnectionRouteOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteVpnConnectionRouteOK struct {
}

func (o *DeleteVpnConnectionRouteOK) Error() string {
	return fmt.Sprintf("[POST /DeleteVpnConnectionRoute][%d] deleteVpnConnectionRouteOK ", 200)
}

func (o *DeleteVpnConnectionRouteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
