// Code generated by go-swagger; DO NOT EDIT.

package vpn_connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteVpnConnectionRouteParams creates a new DeleteVpnConnectionRouteParams object
// with the default values initialized.
func NewDeleteVpnConnectionRouteParams() *DeleteVpnConnectionRouteParams {

	return &DeleteVpnConnectionRouteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVpnConnectionRouteParamsWithTimeout creates a new DeleteVpnConnectionRouteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteVpnConnectionRouteParamsWithTimeout(timeout time.Duration) *DeleteVpnConnectionRouteParams {

	return &DeleteVpnConnectionRouteParams{

		timeout: timeout,
	}
}

// NewDeleteVpnConnectionRouteParamsWithContext creates a new DeleteVpnConnectionRouteParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteVpnConnectionRouteParamsWithContext(ctx context.Context) *DeleteVpnConnectionRouteParams {

	return &DeleteVpnConnectionRouteParams{

		Context: ctx,
	}
}

// NewDeleteVpnConnectionRouteParamsWithHTTPClient creates a new DeleteVpnConnectionRouteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteVpnConnectionRouteParamsWithHTTPClient(client *http.Client) *DeleteVpnConnectionRouteParams {

	return &DeleteVpnConnectionRouteParams{
		HTTPClient: client,
	}
}

/*DeleteVpnConnectionRouteParams contains all the parameters to send to the API endpoint
for the delete vpn connection route operation typically these are written to a http.Request
*/
type DeleteVpnConnectionRouteParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete vpn connection route params
func (o *DeleteVpnConnectionRouteParams) WithTimeout(timeout time.Duration) *DeleteVpnConnectionRouteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete vpn connection route params
func (o *DeleteVpnConnectionRouteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete vpn connection route params
func (o *DeleteVpnConnectionRouteParams) WithContext(ctx context.Context) *DeleteVpnConnectionRouteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete vpn connection route params
func (o *DeleteVpnConnectionRouteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete vpn connection route params
func (o *DeleteVpnConnectionRouteParams) WithHTTPClient(client *http.Client) *DeleteVpnConnectionRouteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete vpn connection route params
func (o *DeleteVpnConnectionRouteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVpnConnectionRouteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
