// Code generated by go-swagger; DO NOT EDIT.

package vpn_connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadVpnConnectionsReader is a Reader for the ReadVpnConnections structure.
type ReadVpnConnectionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadVpnConnectionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadVpnConnectionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadVpnConnectionsOK creates a ReadVpnConnectionsOK with default headers values
func NewReadVpnConnectionsOK() *ReadVpnConnectionsOK {
	return &ReadVpnConnectionsOK{}
}

/*ReadVpnConnectionsOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadVpnConnectionsOK struct {
}

func (o *ReadVpnConnectionsOK) Error() string {
	return fmt.Sprintf("[POST /ReadVpnConnections][%d] readVpnConnectionsOK ", 200)
}

func (o *ReadVpnConnectionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
