// Code generated by go-swagger; DO NOT EDIT.

package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateVmsParams creates a new CreateVmsParams object
// with the default values initialized.
func NewCreateVmsParams() *CreateVmsParams {

	return &CreateVmsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateVmsParamsWithTimeout creates a new CreateVmsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateVmsParamsWithTimeout(timeout time.Duration) *CreateVmsParams {

	return &CreateVmsParams{

		timeout: timeout,
	}
}

// NewCreateVmsParamsWithContext creates a new CreateVmsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateVmsParamsWithContext(ctx context.Context) *CreateVmsParams {

	return &CreateVmsParams{

		Context: ctx,
	}
}

// NewCreateVmsParamsWithHTTPClient creates a new CreateVmsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateVmsParamsWithHTTPClient(client *http.Client) *CreateVmsParams {

	return &CreateVmsParams{
		HTTPClient: client,
	}
}

/*CreateVmsParams contains all the parameters to send to the API endpoint
for the create vms operation typically these are written to a http.Request
*/
type CreateVmsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create vms params
func (o *CreateVmsParams) WithTimeout(timeout time.Duration) *CreateVmsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create vms params
func (o *CreateVmsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create vms params
func (o *CreateVmsParams) WithContext(ctx context.Context) *CreateVmsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create vms params
func (o *CreateVmsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create vms params
func (o *CreateVmsParams) WithHTTPClient(client *http.Client) *CreateVmsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create vms params
func (o *CreateVmsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreateVmsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
