// Code generated by go-swagger; DO NOT EDIT.

package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateVmsReader is a Reader for the CreateVms structure.
type CreateVmsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateVmsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateVmsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateVmsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateVmsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateVmsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateVmsOK creates a CreateVmsOK with default headers values
func NewCreateVmsOK() *CreateVmsOK {
	return &CreateVmsOK{}
}

/*CreateVmsOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreateVmsOK struct {
}

func (o *CreateVmsOK) Error() string {
	return fmt.Sprintf("[POST /CreateVms][%d] createVmsOK ", 200)
}

func (o *CreateVmsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateVmsBadRequest creates a CreateVmsBadRequest with default headers values
func NewCreateVmsBadRequest() *CreateVmsBadRequest {
	return &CreateVmsBadRequest{}
}

/*CreateVmsBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type CreateVmsBadRequest struct {
}

func (o *CreateVmsBadRequest) Error() string {
	return fmt.Sprintf("[POST /CreateVms][%d] createVmsBadRequest ", 400)
}

func (o *CreateVmsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateVmsUnauthorized creates a CreateVmsUnauthorized with default headers values
func NewCreateVmsUnauthorized() *CreateVmsUnauthorized {
	return &CreateVmsUnauthorized{}
}

/*CreateVmsUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type CreateVmsUnauthorized struct {
}

func (o *CreateVmsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /CreateVms][%d] createVmsUnauthorized ", 401)
}

func (o *CreateVmsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateVmsInternalServerError creates a CreateVmsInternalServerError with default headers values
func NewCreateVmsInternalServerError() *CreateVmsInternalServerError {
	return &CreateVmsInternalServerError{}
}

/*CreateVmsInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type CreateVmsInternalServerError struct {
}

func (o *CreateVmsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /CreateVms][%d] createVmsInternalServerError ", 500)
}

func (o *CreateVmsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
