// Code generated by go-swagger; DO NOT EDIT.

package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteVmsReader is a Reader for the DeleteVms structure.
type DeleteVmsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteVmsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteVmsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteVmsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteVmsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteVmsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteVmsOK creates a DeleteVmsOK with default headers values
func NewDeleteVmsOK() *DeleteVmsOK {
	return &DeleteVmsOK{}
}

/*DeleteVmsOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteVmsOK struct {
}

func (o *DeleteVmsOK) Error() string {
	return fmt.Sprintf("[POST /DeleteVms][%d] deleteVmsOK ", 200)
}

func (o *DeleteVmsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteVmsBadRequest creates a DeleteVmsBadRequest with default headers values
func NewDeleteVmsBadRequest() *DeleteVmsBadRequest {
	return &DeleteVmsBadRequest{}
}

/*DeleteVmsBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type DeleteVmsBadRequest struct {
}

func (o *DeleteVmsBadRequest) Error() string {
	return fmt.Sprintf("[POST /DeleteVms][%d] deleteVmsBadRequest ", 400)
}

func (o *DeleteVmsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteVmsUnauthorized creates a DeleteVmsUnauthorized with default headers values
func NewDeleteVmsUnauthorized() *DeleteVmsUnauthorized {
	return &DeleteVmsUnauthorized{}
}

/*DeleteVmsUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type DeleteVmsUnauthorized struct {
}

func (o *DeleteVmsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /DeleteVms][%d] deleteVmsUnauthorized ", 401)
}

func (o *DeleteVmsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteVmsInternalServerError creates a DeleteVmsInternalServerError with default headers values
func NewDeleteVmsInternalServerError() *DeleteVmsInternalServerError {
	return &DeleteVmsInternalServerError{}
}

/*DeleteVmsInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type DeleteVmsInternalServerError struct {
}

func (o *DeleteVmsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /DeleteVms][%d] deleteVmsInternalServerError ", 500)
}

func (o *DeleteVmsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
