// Code generated by go-swagger; DO NOT EDIT.

package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRebootVmsParams creates a new RebootVmsParams object
// with the default values initialized.
func NewRebootVmsParams() *RebootVmsParams {

	return &RebootVmsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRebootVmsParamsWithTimeout creates a new RebootVmsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRebootVmsParamsWithTimeout(timeout time.Duration) *RebootVmsParams {

	return &RebootVmsParams{

		timeout: timeout,
	}
}

// NewRebootVmsParamsWithContext creates a new RebootVmsParams object
// with the default values initialized, and the ability to set a context for a request
func NewRebootVmsParamsWithContext(ctx context.Context) *RebootVmsParams {

	return &RebootVmsParams{

		Context: ctx,
	}
}

// NewRebootVmsParamsWithHTTPClient creates a new RebootVmsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRebootVmsParamsWithHTTPClient(client *http.Client) *RebootVmsParams {

	return &RebootVmsParams{
		HTTPClient: client,
	}
}

/*RebootVmsParams contains all the parameters to send to the API endpoint
for the reboot vms operation typically these are written to a http.Request
*/
type RebootVmsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the reboot vms params
func (o *RebootVmsParams) WithTimeout(timeout time.Duration) *RebootVmsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reboot vms params
func (o *RebootVmsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reboot vms params
func (o *RebootVmsParams) WithContext(ctx context.Context) *RebootVmsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reboot vms params
func (o *RebootVmsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reboot vms params
func (o *RebootVmsParams) WithHTTPClient(client *http.Client) *RebootVmsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reboot vms params
func (o *RebootVmsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RebootVmsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
