// Code generated by go-swagger; DO NOT EDIT.

package keypair

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateKeypairParams creates a new CreateKeypairParams object
// with the default values initialized.
func NewCreateKeypairParams() *CreateKeypairParams {

	return &CreateKeypairParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateKeypairParamsWithTimeout creates a new CreateKeypairParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateKeypairParamsWithTimeout(timeout time.Duration) *CreateKeypairParams {

	return &CreateKeypairParams{

		timeout: timeout,
	}
}

// NewCreateKeypairParamsWithContext creates a new CreateKeypairParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateKeypairParamsWithContext(ctx context.Context) *CreateKeypairParams {

	return &CreateKeypairParams{

		Context: ctx,
	}
}

// NewCreateKeypairParamsWithHTTPClient creates a new CreateKeypairParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateKeypairParamsWithHTTPClient(client *http.Client) *CreateKeypairParams {

	return &CreateKeypairParams{
		HTTPClient: client,
	}
}

/*CreateKeypairParams contains all the parameters to send to the API endpoint
for the create keypair operation typically these are written to a http.Request
*/
type CreateKeypairParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create keypair params
func (o *CreateKeypairParams) WithTimeout(timeout time.Duration) *CreateKeypairParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create keypair params
func (o *CreateKeypairParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create keypair params
func (o *CreateKeypairParams) WithContext(ctx context.Context) *CreateKeypairParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create keypair params
func (o *CreateKeypairParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create keypair params
func (o *CreateKeypairParams) WithHTTPClient(client *http.Client) *CreateKeypairParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create keypair params
func (o *CreateKeypairParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreateKeypairParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
