// Code generated by go-swagger; DO NOT EDIT.

package keypair

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadKeypairsReader is a Reader for the ReadKeypairs structure.
type ReadKeypairsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadKeypairsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadKeypairsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewReadKeypairsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewReadKeypairsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewReadKeypairsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadKeypairsOK creates a ReadKeypairsOK with default headers values
func NewReadKeypairsOK() *ReadKeypairsOK {
	return &ReadKeypairsOK{}
}

/*ReadKeypairsOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadKeypairsOK struct {
}

func (o *ReadKeypairsOK) Error() string {
	return fmt.Sprintf("[POST /ReadKeypairs][%d] readKeypairsOK ", 200)
}

func (o *ReadKeypairsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewReadKeypairsBadRequest creates a ReadKeypairsBadRequest with default headers values
func NewReadKeypairsBadRequest() *ReadKeypairsBadRequest {
	return &ReadKeypairsBadRequest{}
}

/*ReadKeypairsBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type ReadKeypairsBadRequest struct {
}

func (o *ReadKeypairsBadRequest) Error() string {
	return fmt.Sprintf("[POST /ReadKeypairs][%d] readKeypairsBadRequest ", 400)
}

func (o *ReadKeypairsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewReadKeypairsUnauthorized creates a ReadKeypairsUnauthorized with default headers values
func NewReadKeypairsUnauthorized() *ReadKeypairsUnauthorized {
	return &ReadKeypairsUnauthorized{}
}

/*ReadKeypairsUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type ReadKeypairsUnauthorized struct {
}

func (o *ReadKeypairsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /ReadKeypairs][%d] readKeypairsUnauthorized ", 401)
}

func (o *ReadKeypairsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewReadKeypairsInternalServerError creates a ReadKeypairsInternalServerError with default headers values
func NewReadKeypairsInternalServerError() *ReadKeypairsInternalServerError {
	return &ReadKeypairsInternalServerError{}
}

/*ReadKeypairsInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type ReadKeypairsInternalServerError struct {
}

func (o *ReadKeypairsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /ReadKeypairs][%d] readKeypairsInternalServerError ", 500)
}

func (o *ReadKeypairsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
