// Code generated by go-swagger; DO NOT EDIT.

package keypair

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadKeypairsParams creates a new ReadKeypairsParams object
// with the default values initialized.
func NewReadKeypairsParams() *ReadKeypairsParams {

	return &ReadKeypairsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadKeypairsParamsWithTimeout creates a new ReadKeypairsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadKeypairsParamsWithTimeout(timeout time.Duration) *ReadKeypairsParams {

	return &ReadKeypairsParams{

		timeout: timeout,
	}
}

// NewReadKeypairsParamsWithContext creates a new ReadKeypairsParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadKeypairsParamsWithContext(ctx context.Context) *ReadKeypairsParams {

	return &ReadKeypairsParams{

		Context: ctx,
	}
}

// NewReadKeypairsParamsWithHTTPClient creates a new ReadKeypairsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadKeypairsParamsWithHTTPClient(client *http.Client) *ReadKeypairsParams {

	return &ReadKeypairsParams{
		HTTPClient: client,
	}
}

/*ReadKeypairsParams contains all the parameters to send to the API endpoint
for the read keypairs operation typically these are written to a http.Request
*/
type ReadKeypairsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read keypairs params
func (o *ReadKeypairsParams) WithTimeout(timeout time.Duration) *ReadKeypairsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read keypairs params
func (o *ReadKeypairsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read keypairs params
func (o *ReadKeypairsParams) WithContext(ctx context.Context) *ReadKeypairsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read keypairs params
func (o *ReadKeypairsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read keypairs params
func (o *ReadKeypairsParams) WithHTTPClient(client *http.Client) *ReadKeypairsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read keypairs params
func (o *ReadKeypairsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReadKeypairsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
