// Code generated by go-swagger; DO NOT EDIT.

package security_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateSecurityGroupReader is a Reader for the CreateSecurityGroup structure.
type CreateSecurityGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSecurityGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateSecurityGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateSecurityGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateSecurityGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateSecurityGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateSecurityGroupOK creates a CreateSecurityGroupOK with default headers values
func NewCreateSecurityGroupOK() *CreateSecurityGroupOK {
	return &CreateSecurityGroupOK{}
}

/*CreateSecurityGroupOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreateSecurityGroupOK struct {
}

func (o *CreateSecurityGroupOK) Error() string {
	return fmt.Sprintf("[POST /CreateSecurityGroup][%d] createSecurityGroupOK ", 200)
}

func (o *CreateSecurityGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSecurityGroupBadRequest creates a CreateSecurityGroupBadRequest with default headers values
func NewCreateSecurityGroupBadRequest() *CreateSecurityGroupBadRequest {
	return &CreateSecurityGroupBadRequest{}
}

/*CreateSecurityGroupBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type CreateSecurityGroupBadRequest struct {
}

func (o *CreateSecurityGroupBadRequest) Error() string {
	return fmt.Sprintf("[POST /CreateSecurityGroup][%d] createSecurityGroupBadRequest ", 400)
}

func (o *CreateSecurityGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSecurityGroupUnauthorized creates a CreateSecurityGroupUnauthorized with default headers values
func NewCreateSecurityGroupUnauthorized() *CreateSecurityGroupUnauthorized {
	return &CreateSecurityGroupUnauthorized{}
}

/*CreateSecurityGroupUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type CreateSecurityGroupUnauthorized struct {
}

func (o *CreateSecurityGroupUnauthorized) Error() string {
	return fmt.Sprintf("[POST /CreateSecurityGroup][%d] createSecurityGroupUnauthorized ", 401)
}

func (o *CreateSecurityGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSecurityGroupInternalServerError creates a CreateSecurityGroupInternalServerError with default headers values
func NewCreateSecurityGroupInternalServerError() *CreateSecurityGroupInternalServerError {
	return &CreateSecurityGroupInternalServerError{}
}

/*CreateSecurityGroupInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type CreateSecurityGroupInternalServerError struct {
}

func (o *CreateSecurityGroupInternalServerError) Error() string {
	return fmt.Sprintf("[POST /CreateSecurityGroup][%d] createSecurityGroupInternalServerError ", 500)
}

func (o *CreateSecurityGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
