// Code generated by go-swagger; DO NOT EDIT.

package security_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteSecurityGroupReader is a Reader for the DeleteSecurityGroup structure.
type DeleteSecurityGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSecurityGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSecurityGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteSecurityGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteSecurityGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteSecurityGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSecurityGroupOK creates a DeleteSecurityGroupOK with default headers values
func NewDeleteSecurityGroupOK() *DeleteSecurityGroupOK {
	return &DeleteSecurityGroupOK{}
}

/*DeleteSecurityGroupOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteSecurityGroupOK struct {
}

func (o *DeleteSecurityGroupOK) Error() string {
	return fmt.Sprintf("[POST /DeleteSecurityGroup][%d] deleteSecurityGroupOK ", 200)
}

func (o *DeleteSecurityGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSecurityGroupBadRequest creates a DeleteSecurityGroupBadRequest with default headers values
func NewDeleteSecurityGroupBadRequest() *DeleteSecurityGroupBadRequest {
	return &DeleteSecurityGroupBadRequest{}
}

/*DeleteSecurityGroupBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type DeleteSecurityGroupBadRequest struct {
}

func (o *DeleteSecurityGroupBadRequest) Error() string {
	return fmt.Sprintf("[POST /DeleteSecurityGroup][%d] deleteSecurityGroupBadRequest ", 400)
}

func (o *DeleteSecurityGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSecurityGroupUnauthorized creates a DeleteSecurityGroupUnauthorized with default headers values
func NewDeleteSecurityGroupUnauthorized() *DeleteSecurityGroupUnauthorized {
	return &DeleteSecurityGroupUnauthorized{}
}

/*DeleteSecurityGroupUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type DeleteSecurityGroupUnauthorized struct {
}

func (o *DeleteSecurityGroupUnauthorized) Error() string {
	return fmt.Sprintf("[POST /DeleteSecurityGroup][%d] deleteSecurityGroupUnauthorized ", 401)
}

func (o *DeleteSecurityGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSecurityGroupInternalServerError creates a DeleteSecurityGroupInternalServerError with default headers values
func NewDeleteSecurityGroupInternalServerError() *DeleteSecurityGroupInternalServerError {
	return &DeleteSecurityGroupInternalServerError{}
}

/*DeleteSecurityGroupInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type DeleteSecurityGroupInternalServerError struct {
}

func (o *DeleteSecurityGroupInternalServerError) Error() string {
	return fmt.Sprintf("[POST /DeleteSecurityGroup][%d] deleteSecurityGroupInternalServerError ", 500)
}

func (o *DeleteSecurityGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
