// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadVmsHealthReader is a Reader for the ReadVmsHealth structure.
type ReadVmsHealthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadVmsHealthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadVmsHealthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadVmsHealthOK creates a ReadVmsHealthOK with default headers values
func NewReadVmsHealthOK() *ReadVmsHealthOK {
	return &ReadVmsHealthOK{}
}

/*ReadVmsHealthOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadVmsHealthOK struct {
}

func (o *ReadVmsHealthOK) Error() string {
	return fmt.Sprintf("[POST /ReadVmsHealth][%d] readVmsHealthOK ", 200)
}

func (o *ReadVmsHealthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
