// Code generated by go-swagger; DO NOT EDIT.

package net_access_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateNetAccessPointReader is a Reader for the CreateNetAccessPoint structure.
type CreateNetAccessPointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNetAccessPointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateNetAccessPointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateNetAccessPointOK creates a CreateNetAccessPointOK with default headers values
func NewCreateNetAccessPointOK() *CreateNetAccessPointOK {
	return &CreateNetAccessPointOK{}
}

/*CreateNetAccessPointOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreateNetAccessPointOK struct {
}

func (o *CreateNetAccessPointOK) Error() string {
	return fmt.Sprintf("[POST /CreateNetAccessPoint][%d] createNetAccessPointOK ", 200)
}

func (o *CreateNetAccessPointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
