// Code generated by go-swagger; DO NOT EDIT.

package net_access_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteNetAccessPointReader is a Reader for the DeleteNetAccessPoint structure.
type DeleteNetAccessPointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNetAccessPointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteNetAccessPointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteNetAccessPointOK creates a DeleteNetAccessPointOK with default headers values
func NewDeleteNetAccessPointOK() *DeleteNetAccessPointOK {
	return &DeleteNetAccessPointOK{}
}

/*DeleteNetAccessPointOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type DeleteNetAccessPointOK struct {
}

func (o *DeleteNetAccessPointOK) Error() string {
	return fmt.Sprintf("[POST /DeleteNetAccessPoint][%d] deleteNetAccessPointOK ", 200)
}

func (o *DeleteNetAccessPointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
