// Code generated by go-swagger; DO NOT EDIT.

package net_access_point

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadNetAccessPointServicesReader is a Reader for the ReadNetAccessPointServices structure.
type ReadNetAccessPointServicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadNetAccessPointServicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadNetAccessPointServicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadNetAccessPointServicesOK creates a ReadNetAccessPointServicesOK with default headers values
func NewReadNetAccessPointServicesOK() *ReadNetAccessPointServicesOK {
	return &ReadNetAccessPointServicesOK{}
}

/*ReadNetAccessPointServicesOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type ReadNetAccessPointServicesOK struct {
}

func (o *ReadNetAccessPointServicesOK) Error() string {
	return fmt.Sprintf("[POST /ReadNetAccessPointServices][%d] readNetAccessPointServicesOK ", 200)
}

func (o *ReadNetAccessPointServicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
