// Code generated by go-swagger; DO NOT EDIT.

package route_table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadRouteTablesParams creates a new ReadRouteTablesParams object
// with the default values initialized.
func NewReadRouteTablesParams() *ReadRouteTablesParams {

	return &ReadRouteTablesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadRouteTablesParamsWithTimeout creates a new ReadRouteTablesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadRouteTablesParamsWithTimeout(timeout time.Duration) *ReadRouteTablesParams {

	return &ReadRouteTablesParams{

		timeout: timeout,
	}
}

// NewReadRouteTablesParamsWithContext creates a new ReadRouteTablesParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadRouteTablesParamsWithContext(ctx context.Context) *ReadRouteTablesParams {

	return &ReadRouteTablesParams{

		Context: ctx,
	}
}

// NewReadRouteTablesParamsWithHTTPClient creates a new ReadRouteTablesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadRouteTablesParamsWithHTTPClient(client *http.Client) *ReadRouteTablesParams {

	return &ReadRouteTablesParams{
		HTTPClient: client,
	}
}

/*ReadRouteTablesParams contains all the parameters to send to the API endpoint
for the read route tables operation typically these are written to a http.Request
*/
type ReadRouteTablesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read route tables params
func (o *ReadRouteTablesParams) WithTimeout(timeout time.Duration) *ReadRouteTablesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read route tables params
func (o *ReadRouteTablesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read route tables params
func (o *ReadRouteTablesParams) WithContext(ctx context.Context) *ReadRouteTablesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read route tables params
func (o *ReadRouteTablesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read route tables params
func (o *ReadRouteTablesParams) WithHTTPClient(client *http.Client) *ReadRouteTablesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read route tables params
func (o *ReadRouteTablesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReadRouteTablesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
