// Code generated by go-swagger; DO NOT EDIT.

package route_table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new route table API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for route table API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreateRouteTable create route table API
*/
func (a *Client) CreateRouteTable(params *CreateRouteTableParams, authInfo runtime.ClientAuthInfoWriter) (*CreateRouteTableOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateRouteTableParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "CreateRouteTable",
		Method:             "POST",
		PathPattern:        "/CreateRouteTable",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateRouteTableReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateRouteTableOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateRouteTable: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteRouteTable delete route table API
*/
func (a *Client) DeleteRouteTable(params *DeleteRouteTableParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteRouteTableOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteRouteTableParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DeleteRouteTable",
		Method:             "POST",
		PathPattern:        "/DeleteRouteTable",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteRouteTableReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteRouteTableOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteRouteTable: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
LinkRouteTable link route table API
*/
func (a *Client) LinkRouteTable(params *LinkRouteTableParams, authInfo runtime.ClientAuthInfoWriter) (*LinkRouteTableOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewLinkRouteTableParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "LinkRouteTable",
		Method:             "POST",
		PathPattern:        "/LinkRouteTable",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &LinkRouteTableReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*LinkRouteTableOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for LinkRouteTable: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ReadRouteTables read route tables API
*/
func (a *Client) ReadRouteTables(params *ReadRouteTablesParams, authInfo runtime.ClientAuthInfoWriter) (*ReadRouteTablesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReadRouteTablesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "ReadRouteTables",
		Method:             "POST",
		PathPattern:        "/ReadRouteTables",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ReadRouteTablesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReadRouteTablesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ReadRouteTables: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UnlinkRouteTable unlink route table API
*/
func (a *Client) UnlinkRouteTable(params *UnlinkRouteTableParams, authInfo runtime.ClientAuthInfoWriter) (*UnlinkRouteTableOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUnlinkRouteTableParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "UnlinkRouteTable",
		Method:             "POST",
		PathPattern:        "/UnlinkRouteTable",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UnlinkRouteTableReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UnlinkRouteTableOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for UnlinkRouteTable: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
