// Code generated by go-swagger; DO NOT EDIT.

package route_table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUnlinkRouteTableParams creates a new UnlinkRouteTableParams object
// with the default values initialized.
func NewUnlinkRouteTableParams() *UnlinkRouteTableParams {

	return &UnlinkRouteTableParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUnlinkRouteTableParamsWithTimeout creates a new UnlinkRouteTableParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUnlinkRouteTableParamsWithTimeout(timeout time.Duration) *UnlinkRouteTableParams {

	return &UnlinkRouteTableParams{

		timeout: timeout,
	}
}

// NewUnlinkRouteTableParamsWithContext creates a new UnlinkRouteTableParams object
// with the default values initialized, and the ability to set a context for a request
func NewUnlinkRouteTableParamsWithContext(ctx context.Context) *UnlinkRouteTableParams {

	return &UnlinkRouteTableParams{

		Context: ctx,
	}
}

// NewUnlinkRouteTableParamsWithHTTPClient creates a new UnlinkRouteTableParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUnlinkRouteTableParamsWithHTTPClient(client *http.Client) *UnlinkRouteTableParams {

	return &UnlinkRouteTableParams{
		HTTPClient: client,
	}
}

/*UnlinkRouteTableParams contains all the parameters to send to the API endpoint
for the unlink route table operation typically these are written to a http.Request
*/
type UnlinkRouteTableParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the unlink route table params
func (o *UnlinkRouteTableParams) WithTimeout(timeout time.Duration) *UnlinkRouteTableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unlink route table params
func (o *UnlinkRouteTableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unlink route table params
func (o *UnlinkRouteTableParams) WithContext(ctx context.Context) *UnlinkRouteTableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unlink route table params
func (o *UnlinkRouteTableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unlink route table params
func (o *UnlinkRouteTableParams) WithHTTPClient(client *http.Client) *UnlinkRouteTableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unlink route table params
func (o *UnlinkRouteTableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UnlinkRouteTableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
