// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateTagsReader is a Reader for the CreateTags structure.
type CreateTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateTagsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateTagsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateTagsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateTagsOK creates a CreateTagsOK with default headers values
func NewCreateTagsOK() *CreateTagsOK {
	return &CreateTagsOK{}
}

/*CreateTagsOK handles this case with default header values.

The HTTP 200 response (OK).
*/
type CreateTagsOK struct {
}

func (o *CreateTagsOK) Error() string {
	return fmt.Sprintf("[POST /CreateTags][%d] createTagsOK ", 200)
}

func (o *CreateTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTagsBadRequest creates a CreateTagsBadRequest with default headers values
func NewCreateTagsBadRequest() *CreateTagsBadRequest {
	return &CreateTagsBadRequest{}
}

/*CreateTagsBadRequest handles this case with default header values.

The HTTP 400 response (Bad Request).
*/
type CreateTagsBadRequest struct {
}

func (o *CreateTagsBadRequest) Error() string {
	return fmt.Sprintf("[POST /CreateTags][%d] createTagsBadRequest ", 400)
}

func (o *CreateTagsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTagsUnauthorized creates a CreateTagsUnauthorized with default headers values
func NewCreateTagsUnauthorized() *CreateTagsUnauthorized {
	return &CreateTagsUnauthorized{}
}

/*CreateTagsUnauthorized handles this case with default header values.

The HTTP 401 response (Unauthorized).
*/
type CreateTagsUnauthorized struct {
}

func (o *CreateTagsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /CreateTags][%d] createTagsUnauthorized ", 401)
}

func (o *CreateTagsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTagsInternalServerError creates a CreateTagsInternalServerError with default headers values
func NewCreateTagsInternalServerError() *CreateTagsInternalServerError {
	return &CreateTagsInternalServerError{}
}

/*CreateTagsInternalServerError handles this case with default header values.

The HTTP 500 response (Internal Server Error).
*/
type CreateTagsInternalServerError struct {
}

func (o *CreateTagsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /CreateTags][%d] createTagsInternalServerError ", 500)
}

func (o *CreateTagsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
