// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateTagsParams creates a new CreateTagsParams object
// with the default values initialized.
func NewCreateTagsParams() *CreateTagsParams {

	return &CreateTagsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTagsParamsWithTimeout creates a new CreateTagsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateTagsParamsWithTimeout(timeout time.Duration) *CreateTagsParams {

	return &CreateTagsParams{

		timeout: timeout,
	}
}

// NewCreateTagsParamsWithContext creates a new CreateTagsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateTagsParamsWithContext(ctx context.Context) *CreateTagsParams {

	return &CreateTagsParams{

		Context: ctx,
	}
}

// NewCreateTagsParamsWithHTTPClient creates a new CreateTagsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateTagsParamsWithHTTPClient(client *http.Client) *CreateTagsParams {

	return &CreateTagsParams{
		HTTPClient: client,
	}
}

/*CreateTagsParams contains all the parameters to send to the API endpoint
for the create tags operation typically these are written to a http.Request
*/
type CreateTagsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create tags params
func (o *CreateTagsParams) WithTimeout(timeout time.Duration) *CreateTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create tags params
func (o *CreateTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create tags params
func (o *CreateTagsParams) WithContext(ctx context.Context) *CreateTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create tags params
func (o *CreateTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create tags params
func (o *CreateTagsParams) WithHTTPClient(client *http.Client) *CreateTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create tags params
func (o *CreateTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
